package com.demo.multithread;

import java.io.BufferedReader;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class ReadFile {
    public static void main(String[] args) {
	try {
	    Map<String, String> map = new HashMap<String, String>();
	    addMap(map);
	    // 读取指定文件夹下的所有文件
	    String filepath = "D:\\workspace\\wp1\\wms-web\\src\\main\\java\\com\\wumart\\scm\\wms\\web\\controller";// 给我你的目录文件夹路径

	    extracted(map, filepath);
	} catch (Exception e) {
	    e.printStackTrace();
	}
    }

    private static void extracted(Map<String, String> map, String filepath) {
	File file = new File(filepath);
	if (!file.isDirectory()) {
	} else if (file.isDirectory()) {
	    String[] filelist = file.list();

	    for (int i = 0; i < filelist.length; i++) {

		extracted(map, filepath + "\\" + filelist[i]);
		File readfile = new File(filepath + "\\" + filelist[i]);
		map.forEach((k, v) -> {
		    try {
			FileReader in = new FileReader(readfile);
			BufferedReader bufIn = new BufferedReader(in);
			// 内存流, 作为临时流
			CharArrayWriter tempStream = new CharArrayWriter();
			// 替换
			String line = null;
			while ((line = bufIn.readLine()) != null) {
			    if (line.contains("return")) {
				// 替换每行中, 符合条件的字符串
				// 1.符合替换return Response.writeError(\"新增或者更新商家商品发生异常, 原因: \" ,
				// ExceptionUtils.getRootCauseMessage(e));
				if (line.contains(k) && String.valueOf(line.charAt(line.indexOf(k) - 2)).equals("(")
					&& !line.contains("String.format")
					&& line.contains("ExceptionUtils.getRootCauseMessage(e)")) {
				    
				    //特别注意  必须要用I18nHolder.format(I18nMessageCode.ADD_CUS_EPT_REASON  
				    //不能后面加上)
				    line = line.replace("+", ",");
				    line = line.replace(";", ");");
				    line = line.replace("\"" + k + "\"", v);
				} else if (line.contains(k) && line.contains("String.format")) {
				    line = line.replace(k, v);
				}else if(line.contains(k)) {
				    // 2.符合替换 return Response.writeError("新增或者更新商家商品发生异常")
				    line = line.replace("\"" + k + "\"", v);
				    line = line.replace( k, v);
				}
			    }
			    // 将该行写入内存
			    tempStream.write(line);
			    // 添加换行符
			    tempStream.append("\n");

			}
			// 关闭 输入流
			bufIn.close();
			// 将内存中的流 写入 文件
			FileWriter out = new FileWriter(readfile);
			tempStream.writeTo(out);
			out.close();

		    } catch (FileNotFoundException e) {
		    } catch (IOException e) {
		    }
		});
	    }

	    System.out.println("---------- 所有文件操作完毕 ----------");
	}

    }
    private static void addMap(Map<String, String> map) {
	map.put("存储类型Id为空","I18nHolder.format(I18nMessageCode.STORAGE_TYPE_ID_EMPTY)");
	map.put("仓位为空","I18nHolder.format(I18nMessageCode.BIN_EMPTY)");
	map.put("没有可以创建任务的组包数据","I18nHolder.format(I18nMessageCode.NOT_CREATE_TASK_DATA)");
	map.put("日期类型不正确","I18nHolder.format(I18nMessageCode.TIME_TYPE_NOT_CORRECT)");
	map.put("删除id为空","I18nHolder.format(I18nMessageCode.DEL_ID_EMPTY)");
	map.put("授权方不存在","I18nHolder.format(I18nMessageCode.EM_NOEXIT)");
	map.put("仓位为空","I18nHolder.format(I18nMessageCode.BIN_EMPTY)");
	
//      map.put("查询失败", "I18nHolder.format(I18nMessageCode.QUERY_FAILURE)");
//	map.put("列表查询异常", "I18nHolder.format(I18nMessageCode.LIST_QUERY_EXCEPTION)");
//	map.put("新增出现异常", "I18nHolder.format(I18nMessageCode.ADD_EXCEPTION)");
//	map.put("新增成功", "I18nHolder.format(I18nMessageCode.ADD_SUCCESS)");
//	map.put("添加失败", "I18nHolder.format(I18nMessageCode.ADD_FAILURE)");
//	map.put("删除成功", "I18nHolder.format(I18nMessageCode.DELETE_SUCCESS)");
//	map.put("删除失败", "I18nHolder.format(I18nMessageCode.DELETE_FAILURE)");
//	map.put("更新成功", "I18nHolder.format(I18nMessageCode.UPDATE_SUCCESS)");
//	map.put("更新失败", "I18nHolder.format(I18nMessageCode.UPDATE_FAILURE)");
//	map.put("添加操作失败", "I18nHolder.format(I18nMessageCode.ADD_HANDLE_FAILURE)");
//	map.put("删除操作失败", "I18nHolder.format(I18nMessageCode.DELETE_HANDLE_FAILURE)");
//	map.put("更新操作失败", "I18nHolder.format(I18nMessageCode.UPDATE_HANDLE_FAILURE)");
//	map.put("查询操作失败", "I18nHolder.format(I18nMessageCode.QUERY_HANDLE_FAILURE)");
//	map.put("查询出现异常", "I18nHolder.format(I18nMessageCode.QUERY_EXCEPTION)");
//	map.put("注册TU失败", "I18nHolder.format(I18nMessageCode.REGISTER_TU_FAILURE)");
//	map.put("导出失败!", "I18nHolder.format(I18nMessageCode.EXPORT_FAILURE)");
//	map.put("取消操作失败", "I18nHolder.format(I18nMessageCode.CANCEL_HANDLE_FAILURE)");
//	map.put("查询条件为空", "I18nHolder.format(I18nMessageCode.QUERY_CONDITION_NULL)");
//	map.put("开始装载失败", "I18nHolder.format(I18nMessageCode.BEGIN_LOAD_FAILURE)");
//	map.put("装载完成失败", "I18nHolder.format(I18nMessageCode.LOAD_COMPLETE_FAILURE)");
//	map.put("反装载完成失败", "I18nHolder.format(I18nMessageCode.UNLOAD_COMPLETE_FAILURE)");
//	map.put("发车失败", "I18nHolder.format(I18nMessageCode.DEPARTURE_FAILURE)");
//	map.put("离场失败", "I18nHolder.format(I18nMessageCode.AWAY_FAILURE)");
//	map.put("批量离场失败", "I18nHolder.format(I18nMessageCode.BATCHAWAY_FAILURE)");
//	map.put("当前TU已装载托盘,无法进行取消操作", "I18nHolder.format(I18nMessageCode.TU_CANCLE_ERROR)");
//	map.put("当前TU不存在", "I18nHolder.format(I18nMessageCode.CURRENT_TU_NOTEXIST)");
//	map.put("车牌模糊查询失败", "I18nHolder.format(I18nMessageCode.CARTPLATE_VAGUE_QUERY_FAILURE)");
//	map.put("车牌模糊查询异常", "I18nHolder.format(I18nMessageCode.CARTSEPLATE_VAGUEQUERY_EPT)");
//	map.put("取消失败", "I18nHolder.format(I18nMessageCode.CANCLE_FAILURE)");
//	map.put("派车查询失败", "I18nHolder.format(I18nMessageCode.DISPATCH_QUERY_FAILED)");
//	map.put("没有生成派车任务", "I18nHolder.format(I18nMessageCode.NO_DISPATCH_TASK_GENERATED)");
//	map.put("派车失败", "I18nHolder.format(I18nMessageCode.DISPATCH_FAILURE)");
//	map.put("没有车辆排队打印信息", "I18nHolder.format(I18nMessageCode.NO_VEHICLE_QUEUING_PRINT_INFO)");
//	map.put("获取车辆排队打印信息失败!", "I18nHolder.format(I18nMessageCode.FAILED_GET_QUEUE_PRINT_INFO)");
//	map.put("获取装车信息失败", "I18nHolder.format(I18nMessageCode.FAILED_TO_GET_ENTURCK_INFO)");
//	map.put("查看关闭托盘码数量异常", "I18nHolder.format(I18nMessageCode.LOOK_CLOSE_TU_NUM_EPT)");
//	map.put("查询参数为空", "I18nHolder.format(I18nMessageCode.QUERY_PARAM_NULL)");
//	map.put("仓库编码为空", "I18nHolder.format(I18nMessageCode.WHCODE_NULL)");
//	map.put("创建或更新司机信息失败", "I18nHolder.format(I18nMessageCode.FAILED_CREATE_UP_DRI_INFO_REASON)");
//	map.put("创建Tu并派车异常", "I18nHolder.format(I18nMessageCode.FAILED_CREATE_TU_DISPATCH_EPT)");
//	map.put("当前TU已装车,无法进行取消操作", "I18nHolder.format(I18nMessageCode.CURRENT_TU_LOAD_CANNOT_CANCELLED)");
//	map.put("取消TU失败", "I18nHolder.format(I18nMessageCode.CANCLE_TU_FAILURE)");
//	map.put("查询Tu下的hu数量异常", "I18nHolder.format(I18nMessageCode.FAILED_TO_QUERY_NUM_TU_EPT)");
//	map.put("成功", "I18nHolder.format(I18nMessageCode.SUCCESS)");
//	map.put("更新Tu异常", "I18nHolder.format(I18nMessageCode.UPDATE_TU_FAILURE)");
//	map.put("TU编码为空", "I18nHolder.format(I18nMessageCode.TUCODE_NULL)");
//	map.put("TU状态为空", "I18nHolder.format(I18nMessageCode.TU_STATE_NULL)");
//	map.put("tu为空", "I18nHolder.format(I18nMessageCode.TU_NULL)");
//	map.put("发货过账异常", "I18nHolder.format(I18nMessageCode.GOODS_ISSUE_EPT)");
//	map.put("装运点为空", "I18nHolder.format(I18nMessageCode.ENTRUCK_POST_NULL)");
//	map.put("操作人为空", "I18nHolder.format(I18nMessageCode.OPERATOR_NULL)");
//	map.put("消息ID为空", "I18nHolder.format(I18nMessageCode.MESSAGEID_NULL)");
//	map.put("车辆ID为空", "I18nHolder.format(I18nMessageCode.VEHICLEID_NULL)");
//	map.put("获取用户信息为空", "I18nHolder.format(I18nMessageCode.GETUSER_INFO_NULL)");
//	map.put("车牌号不能为空", "I18nHolder.format(I18nMessageCode.LICENSE_PLATE_CANNOT_BE_EMPTY)");
//	map.put("通过车牌号获取TU号和车牌号等相关信息失败", "I18nHolder.format(I18nMessageCode.GET_TU_BY_LICENSE_PLATE_FAILURE)");
//	map.put("通过门编码获取TU号和车牌号等相关信息失败", "I18nHolder.format(I18nMessageCode.GET_TU_BY_CODE_FAILURE)");
//	map.put("查看预装载托盘失败", "I18nHolder.format(I18nMessageCode.FAILED_TO_VIEW_PRE_LOADED_TRAY)");
//	map.put("查看装载托盘状态失败", "I18nHolder.format(I18nMessageCode.FAILED_TO_VIEW_LOAD_TRAY_STATUS)");
//	map.put("查询列表出现异常", "I18nHolder.format(I18nMessageCode.QUERY_LIST_APPEAR_FAILURE)");
//	map.put("新增托盘码失败", "I18nHolder.format(I18nMessageCode.ADD_TRAYCODE_FAILED)");
//	map.put("门编号为空", "I18nHolder.format(I18nMessageCode.DOOR_NUMBER_IS_EMPTY)");
//	map.put("批量新增托盘码失败", "I18nHolder.format(I18nMessageCode.BATCHADD_CONTAINERCODE_FAIL)");
//	map.put("根据集货位获取托盘码失败", "I18nHolder.format(I18nMessageCode.FAILED_PALLET_CODE_FROM_STORAGE)");
//	map.put("通过tu号获取托盘码缓存信息失败", "I18nHolder.format(I18nMessageCode.GET_CTCODE_CACHE_BYTU_FAIL)");
//	map.put("TU号为空", "I18nHolder.format(I18nMessageCode.TU_IS_NULL)");
//	map.put("容器码装车正在进行,结果稍后通知", "I18nHolder.format(I18nMessageCode.CTCODE_LOAD_RESULT_NOTIFY_LATER)");
//	map.put("删除托盘失败", "I18nHolder.format(I18nMessageCode.DELETE_CONTAINER_FAIL)");
//	map.put("删除缓存失败", "I18nHolder.format(I18nMessageCode.DELETE_CACHE_FAIL)");
//	map.put("一键装车正在进行,结果稍后通知", "I18nHolder.format(I18nMessageCode.ONEKEY_LOAD_RESULT_NOTIFY_LATER)");
//	map.put("通过托盘码获取装车相关信息失败", "I18nHolder.format(I18nMessageCode.GETENTUCKINFO_FAIL_BY_CTCODE)");
//	map.put("whId为空", "I18nHolder.format(I18nMessageCode.WHID_NULL)");
//	map.put("装车失败", "I18nHolder.format(I18nMessageCode.ENTUCK_FAIL)");
//	map.put("装车任务导出失败!", "I18nHolder.format(I18nMessageCode.ENTUCK_TASK_EXPORT_FAIL)");
//	map.put("一键装车失败", "I18nHolder.format(I18nMessageCode.APPOINT_CTCODE_ENTURCK_FAIL)");
//	map.put("容器码为空", "I18nHolder.format(I18nMessageCode.CTCODE_NULL)");
//	map.put("容器码包含非法字符", "I18nHolder.format(I18nMessageCode.CTCODE_ILLEGAL)");
//	map.put("没有符合要求的容器码", "I18nHolder.format(I18nMessageCode.NO_REQUIRED_CTCODE)");
//	map.put("提交失败", "I18nHolder.format(I18nMessageCode.COMMIT_FAIL)");
//	map.put("容器码不允许出现小写字母", "I18nHolder.format(I18nMessageCode.CTCODE_NOT_ALLOW_LOW_LETTER)");
//	map.put("卸载托盘失败", "I18nHolder.format(I18nMessageCode.PALLET_UNLOAD_FAILED)");
//	map.put("没有符合条件的容器码", "I18nHolder.format(I18nMessageCode.NO_ELIGIBLE_CTCODE)");
//	map.put("批量卸载托盘失败", "I18nHolder.format(I18nMessageCode.BATCH_UNLOAD_CTCODE_FAIL)");
//	map.put("根据集货位，获取托盘数和累计箱数失败", "I18nHolder.format(I18nMessageCode.GET_CTNUM_CUMUBOX_BY_LOCATION)");
//	map.put("通过Tu号获取车牌号和司机信息失败", "I18nHolder.format(I18nMessageCode.GET_PALLET_DRIVER_BY_TU_FAIL)");
//	map.put("查看预装载托盘失败", "I18nHolder.format(I18nMessageCode.VIEW_PRE_LOADED_TRAY_FAIL)");
//	map.put("获取客户失败", "I18nHolder.format(I18nMessageCode.GET_CUSTOMER_FAIL)");
//	map.put("查询工单失败", "I18nHolder.format(I18nMessageCode.QUERY_WORKORDER_FAIL)");
//	map.put("仓库id为空", "I18nHolder.format(I18nMessageCode.WHID_IS_NULL)");
//	map.put("时间为空", "I18nHolder.format(I18nMessageCode.DATE_IS_NULL)");
//	map.put("打印失败", "I18nHolder.format(I18nMessageCode.PRINTING_FAIL)");
//	map.put("打印成功", "I18nHolder.format(I18nMessageCode.PRINTING_SUCESS)");
//	map.put("传入的状态不符合要求[3:卸载;4:装载完成]", "I18nHolder.format(I18nMessageCode.STATE_UNQUALIFIED)");
//	map.put("发货过账执行成功,请注意查收执行结果", "I18nHolder.format(I18nMessageCode.GI_POST_SUCCESS_GET_MSG)");
//	map.put("车辆状态不可用, 无法注册TU", "I18nHolder.format(I18nMessageCode.CART_UNAVAILABLE_NOT_REGISTER_TU)");
//	map.put("司机车辆信息为空", "I18nHolder.format(I18nMessageCode.DRIVER_CART_INFO_IS_NULL)");
//	map.put("wms没有可以更新的司机车辆信息", "I18nHolder.format(I18nMessageCode.WMS_NOT_UPDATE_DRIVER_CART_INFO)");
//	map.put("获取不允许注册多tu仓库失败:", "I18nHolder.format(I18nMessageCode.GET_NOT_REGISTER_MORE_TU_WH_FAIL)");
//	map.put("tu不能为空", "I18nHolder.format(I18nMessageCode.TU_IS_NOT_NULL)");
//	map.put("操作人员编码不能为空", "I18nHolder.format(I18nMessageCode.OPERATOR_CODE_CANNOT_BE_EMPTY)");
//	map.put("通过TU编码找不到可以修改的Tu", "I18nHolder.format(I18nMessageCode.NOTFIND_TU_BY_CODE)");
//	map.put("车辆编码为空", "I18nHolder.format(I18nMessageCode.CART_CODE_IS_NULL)");
//	map.put("装运类型编码为空", "I18nHolder.format(I18nMessageCode.SHIPMENT_TYPE_CODE_IS_EMPTY)");
//	map.put("车型编码为空", "I18nHolder.format(I18nMessageCode.MODEL_CODE_IS_EMPTY)");
//	map.put("IP地址为空", "I18nHolder.format(I18nMessageCode.IP_ADDRESS_IS_NULL)");
//	map.put("分组名为空", "I18nHolder.format(I18nMessageCode.GROUP_NAME_IS_NULL)");
//	map.put("应用名为空", "I18nHolder.format(I18nMessageCode.APPLICATION_NAME_IS_NULL)");
//	map.put("服务不存在", "I18nHolder.format(I18nMessageCode.SERVICE_NOT_EXIST)");
//	map.put("方法不存在", "I18nHolder.format(I18nMessageCode.METHOD_NOT_EXIST)");
//	map.put("分组/版本 不合法", "I18nHolder.format(I18nMessageCode.ILLEGAL_GROUP_VERSION)");
//	map.put("未找到服务提供者", "I18nHolder.format(I18nMessageCode.NOTFIND_SERVICE_PROVIDER)");
//	map.put("加载完成", "I18nHolder.format(I18nMessageCode.LOAD_COMPLETE)");
//	map.put("关闭订单失败,订单号为空", "I18nHolder.format(I18nMessageCode.CLOSE_ORDER_FAIL_NO_IS_NULL)");
//	map.put("根据仓库编码获取仓库信息为空", "I18nHolder.format(I18nMessageCode.GET_WH_BY_WHCODE_IS_NULL)");
//	map.put("授权方编码为空", "I18nHolder.format(I18nMessageCode.EPCODE_IS_NULL)");
//	map.put("商品编码为空", "I18nHolder.format(I18nMessageCode.PRODUCT_CODE_IS_NULL)");
//	map.put("参与校验商品不能超过100条", "I18nHolder.format(I18nMessageCode.NO_MORE_ONE_HUNDRED_PRODUCT)");
//	map.put("商品无未清任务", "I18nHolder.format(I18nMessageCode.NO_TASKS_GOODS)");
//	map.put("商品有未清任务,不允许修改", "I18nHolder.format(I18nMessageCode.NO_TASKS_GOODS_NOTALLOW_UPDATE)");
//	map.put("校验能否修改基本单位异常", "I18nHolder.format(I18nMessageCode.CHECK_UPDATE_UNIT_EPT)");
//	map.put("客户订单号为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_ORDERNO_IS_EMPT)");
//	map.put("os客户订单发货状态", "I18nHolder.format(I18nMessageCode.OS_CUSTOMER_ORDER_SHIP_STATUS)");
//	map.put("getSoDeliveryState执行异常", "I18nHolder.format(I18nMessageCode.GETSODELIVERYSTATE_DO_EPT)");
//	map.put("请求参数为空", "I18nHolder.format(I18nMessageCode.REQUEST_PARAM_IS_NULL)");
//	map.put("商家编码为空", "I18nHolder.format(I18nMessageCode.MERCAHTCODE_IS_NULL)");
//	map.put("库存地编码为空", "I18nHolder.format(I18nMessageCode.STOCK_PLACE_CODE_IS_NULL)");
//	map.put("门店编码为空", "I18nHolder.format(I18nMessageCode.STORE_CODE_IS_NULL)");
//	map.put("os门店在仓库中正在发货的商品", "I18nHolder.format(I18nMessageCode.OS_STORE_ENTURCKPRODUCT_IN_WH)");
//	map.put("getStoreDeliveringProducts执行异常", "I18nHolder.format(I18nMessageCode.GETSTOREDELIVERINGPRODUCTS_EPT)");
//	map.put("供应商编码为空", "I18nHolder.format(I18nMessageCode.SUPPLIER_CODE_IS_NULL)");
//	map.put("R2获取供应商固定仓位主数据异常", "I18nHolder.format(I18nMessageCode.R2_SUPPLIER_LOCA_MASTER_ERROR)");
//	map.put("请检查参数，provinceId", "I18nHolder.format(I18nMessageCode.CHECK_PARAM_PROVINCEID)");
//	map.put("请检查参数，cityId", "I18nHolder.format(I18nMessageCode.CHECK_PARAM_CITYID)");
//	map.put("获取信息失败", "I18nHolder.format(I18nMessageCode.GET_INFO_FAIL)");
//	map.put("数据权限组不能为空", "I18nHolder.format(I18nMessageCode.DATA_AUTH_GROUP_IS_NOT_NULL)");
//	map.put("获取部门信息操作失败", "I18nHolder.format(I18nMessageCode.GET_DEPT_INFO_FAIL)");
//	map.put("用户Id不能为空", "I18nHolder.format(I18nMessageCode.USERID_IS_NOT_NULL)");
//	map.put("重置成功", "I18nHolder.format(I18nMessageCode.RESET_SUCCESSFUL)");
//	map.put("重置密码失败", "I18nHolder.format(I18nMessageCode.RESET_PASSWD_FAIL)");
//	map.put("人员列表导出失败!", "I18nHolder.format(I18nMessageCode.PEOPLE_LIST_EXPORT_FAIL)");
//	map.put("批量删除失败", "I18nHolder.format(I18nMessageCode.BATCH_DELETE_FAIL)");
//	map.put("批量删除操作失败", "I18nHolder.format(I18nMessageCode.BATCH_DELETE_OPER_FAIL)");
//	map.put("错误商家", "I18nHolder.format(I18nMessageCode.MERCHAT_ERROR)");
//	map.put("请选择至少一个用户", "I18nHolder.format(I18nMessageCode.AT_LEAST_CHOSE_ONE_USER)");
//	map.put("批量添加失败", "I18nHolder.format(I18nMessageCode.BATCH_ADD_FAIL)");
//	map.put("批量添加操作失败", "I18nHolder.format(I18nMessageCode.BATCH_ADD_OPER_FAIL)");
//	map.put("参数错误", "I18nHolder.format(I18nMessageCode.PARAM_ERROR)");
//	map.put("异步更新失败", "I18nHolder.format(I18nMessageCode.ASY_UPDATE_FAIL)");
//	map.put("登录失败, 参数错误", "I18nHolder.format(I18nMessageCode.LOGIN_FAIL_PARAM_ERROR)");
//	map.put("登录失败, 参数验证错误", "I18nHolder.format(I18nMessageCode.LOGIN_FAIL_PARAM_CHECK_ERROR)");
//	map.put("登录失败", "I18nHolder.format(I18nMessageCode.LOGIN_FAIL)");
//	map.put("已经退出", "I18nHolder.format(I18nMessageCode.EXITED)");
//	map.put("退出失败", "I18nHolder.format(I18nMessageCode.EXIT_FAILED)");
//	map.put("验证登录失败", "I18nHolder.format(I18nMessageCode.FAILED_TO_VERIFY_LOGIN)");
//	map.put("添加用户失败", "I18nHolder.format(I18nMessageCode.ADD_USER_FAIL)");
//	map.put("添加用户操作失败", "I18nHolder.format(I18nMessageCode.ADD_USER_OPER_FAIL)");
//	map.put("请确认用户是否登录", "I18nHolder.format(I18nMessageCode.CONFIRM_USER_IS_LOGIN)");
//	map.put("用户修改密码失败", "I18nHolder.format(I18nMessageCode.USER_UPDATE_PASSED_FAIL)");
//	map.put("用户修改密码操作失败", "I18nHolder.format(I18nMessageCode.USER_UPDATE_PASSED_OPER_FAIL)");
//	map.put("请输入用户", "I18nHolder.format(I18nMessageCode.PLEASE_INPUT_USER)");
//	map.put("通过部门ID和模糊查询查找用户信息", "I18nHolder.format(I18nMessageCode.VAGUE_QUERY_USER_INFO_BY_DEPT)");
//	map.put("通过用户模糊查询查找用户失败", "I18nHolder.format(I18nMessageCode.VAGUE_USER_QUERY_FAIL)");
//	map.put("判断查询用户失败", "I18nHolder.format(I18nMessageCode.JUDGE_QUERY_USER_FAIL)");
//	map.put("根据部门id查找用户失败", "I18nHolder.format(I18nMessageCode.GET_USER_BY_DEPTID_FAIL)");
//	map.put("仓库参数为空", "I18nHolder.format(I18nMessageCode.WH_PARAM_IS_NULL)");
//	map.put("仓库不存在", "I18nHolder.format(I18nMessageCode.WH_NON_EXIST)");
//	map.put("切换仓库失败", "I18nHolder.format(I18nMessageCode.SWITCH_WH_FAIL)");
//	map.put("切换仓库失败，无该仓库权限", "I18nHolder.format(I18nMessageCode.SWITCH_WH_FAIL_NO_AUTH)");
//	map.put("获取仓库列表异常", "I18nHolder.format(I18nMessageCode.GET_WH_LIST_EPT)");
//	map.put("错误用户组", "I18nHolder.format(I18nMessageCode.USER_GROUP_ERROR)");
//	map.put("添加关联角色失败", "I18nHolder.format(I18nMessageCode.ADD_RELATION_ROLE_FAIL)");
//	map.put("删除关联角色失败", "I18nHolder.format(I18nMessageCode.DELETE_RELATION_ROLE_FAIL)");
//	map.put("进入添加操作页失败", "I18nHolder.format(I18nMessageCode.ENTER_ADD_OPER_PAGE_FAIL)");
//	map.put("没有对应的储存类型信息", "I18nHolder.format(I18nMessageCode.NOT_STORAGE_INFO)");
//	map.put("页面初始化异常", "I18nHolder.format(I18nMessageCode.PAGE_INIT_EPT)");
//	map.put("找不到该授权方", "I18nHolder.format(I18nMessageCode.NOTFIND_EP)");
//	map.put("报溢", "I18nHolder.format(I18nMessageCode.REPORT_OVERFLOW)");
//	map.put("报损", "I18nHolder.format(I18nMessageCode.REPORT_LOSS)");
//	map.put("初始化查询异常", "I18nHolder.format(I18nMessageCode.INIT_QUERY_FAIL)");
//	map.put("库存类别组id为空", "I18nHolder.format(I18nMessageCode.STOCK_CAT_GROUP_ID_IS_NULL)");
//	map.put("查询库存类别成功", "I18nHolder.format(I18nMessageCode.QUERY_INVENT_CAT_SUCCESS)");
//	map.put("保存时data参数为空", "I18nHolder.format(I18nMessageCode.SAVE_DATA_IS_NULL)");
//	map.put("保存时接受者数据为空", "I18nHolder.format(I18nMessageCode.SAVE_DATA_RECEIVE_IS_NULL)");
//	map.put("初始化列表异常", "I18nHolder.format(I18nMessageCode.INIT_LIST_EPT)");
//	map.put("找不到该记录", "I18nHolder.format(I18nMessageCode.NOTFIND_RECORD)");
//	map.put("操作失败", "I18nHolder.format(I18nMessageCode.OPER_FAIL)");
//	map.put("列表初始化出现异常", "I18nHolder.format(I18nMessageCode.LIST_INIT_EPT)");
//	map.put("打印出现异常", "I18nHolder.format(I18nMessageCode.PRINTING_EPT)");
//	map.put("打印数量为空", "I18nHolder.format(I18nMessageCode.PRINTING_NUM_IS_NULL)");
//	map.put("打印机为空", "I18nHolder.format(I18nMessageCode.PRINTING_MACHINE_IS_NULL)");
//	map.put("正在打印中，结果稍后通知", "I18nHolder.format(I18nMessageCode.PRINTING_LATER_NOTIFY)");
//	map.put("业务id为空", "I18nHolder.format(I18nMessageCode.BUSINESS_ID_IS_EMPTY)");
//	map.put("标签类型为空", "I18nHolder.format(I18nMessageCode.LABEL_TYPE_IS_EMPTY)");
//	map.put("获取预览信息失败", "I18nHolder.format(I18nMessageCode.GET_PREVIEW_INFO_FAIL)");
//	map.put("只有WT和SX标签支持任务确认", "I18nHolder.format(I18nMessageCode.ONLY_WT_SX_LABEL_SUP_TASK_CON)");
//	map.put("待打印的容器码为空", "I18nHolder.format(I18nMessageCode.TO_BE_PRINT_CONTAINERCODE_NULL)");
//	map.put("进入更新操作页失败", "I18nHolder.format(I18nMessageCode.ENTER_UPDATE_OPER_FAIL)");
//	map.put("存储类型为空", "I18nHolder.format(I18nMessageCode.STORAGE_TYPE_IS_NULL)");
//	map.put("存储类型id为空", "I18nHolder.format(I18nMessageCode.STORAGE_TYPEID_IS_NULL)");
//	map.put("任务类型为空", "I18nHolder.format(I18nMessageCode.TASK_TYPE_IS_NULL)");
//	map.put("仓位编码为空", "I18nHolder.format(I18nMessageCode.BIN_CODE_IS_NULL)");
//	map.put("根据集货位编码查询仓位为空", "I18nHolder.format(I18nMessageCode.GET_BIN_BY_STORAGE_GOOD_IS_NULL)");
//	map.put("输入的客户编码为空", "I18nHolder.format(I18nMessageCode.PRINT_CUSTOMER_CODE_IS_NULL)");
//	map.put("没有找到KG重量单位", "I18nHolder.format(I18nMessageCode.NOTFIND_KG_UNIT)");
//	map.put("查询类型为空", "I18nHolder.format(I18nMessageCode.QUERY_TYPE_IS_NULL)");
//	map.put("分割字段ID不存在", "I18nHolder.format(I18nMessageCode.SPLIT_FIELD_ID_NOT_EXIST)");
//	map.put("波次归集组不存在", "I18nHolder.format(I18nMessageCode.WAVE_COLLECTION_GROUP_NOT_EXIST)");
//	map.put("拥有者为空", "I18nHolder.format(I18nMessageCode.OWNER_IS_EMPTY)");
//	map.put("仓库处理类型为空", "I18nHolder.format(I18nMessageCode.WH_PROCESS_TYPE_IS_NULL)");
//	map.put("订单类型为空", "I18nHolder.format(I18nMessageCode.ORDER_TYPE_IS_EMPTY)");
//	map.put("订单行项目类型为空", "I18nHolder.format(I18nMessageCode.ORDER_ITEM_TYPE_IS_NULL)");
//	map.put("特殊商品标识为空", "I18nHolder.format(I18nMessageCode.SPECIAL_PRODUCT_TAG_IS_NULL)");
//	map.put("仓库产品组为空", "I18nHolder.format(I18nMessageCode.WH_PRODUCT_GROUP_IS_EMPTY)");
//	map.put("促销标识为空", "I18nHolder.format(I18nMessageCode.PROMOTION_ID_IS_EMPTY)");
//	map.put("客户为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_IS_NULL)");
//	map.put("路线为空", "I18nHolder.format(I18nMessageCode.ROUNT_IS_EMPTY)");
//	map.put("波次模板确定有数据，不允许删除", "I18nHolder.format(I18nMessageCode.WAVE_TEMP_EXIT_DATA_NOT_DELETE)");
//	map.put("服务器负载过高", "I18nHolder.format(I18nMessageCode.SERVER_LOAD_TOO_HIGH)");
//	map.put("请选择时间", "I18nHolder.format(I18nMessageCode.SELETE_TIME)");
//	map.put("初始化仪表盘异常", "I18nHolder.format(I18nMessageCode.INIT_REPORT_EPT)");
//	map.put("参数不对", "I18nHolder.format(I18nMessageCode.PARAM_WRONG)");
//	map.put("url格式不对", "I18nHolder.format(I18nMessageCode.URL_FORMAT_WRONG)");
//	map.put("查询客户为空", "I18nHolder.format(I18nMessageCode.QUERY_CUSTOMER_IS_EMPTY)");
//	map.put("通过仓库Id和仓位编码获取储存类型信息失败", "I18nHolder.format(I18nMessageCode.GET_STO_TYPE_INFO_BY_WHID_FAIL)");
//	map.put("获取用户列表信息失败", "I18nHolder.format(I18nMessageCode.GET_USER_INFO_LIST_FAIL)");
//	map.put("通过存储类型获取仓位列表失败", "I18nHolder.format(I18nMessageCode.GET_BIN_BY_STORAGE_TYPE_FAIL)");
//	map.put("门店id为空", "I18nHolder.format(I18nMessageCode.SHOP_ID_NULL)");
//	map.put("通过步骤列表失败", "I18nHolder.format(I18nMessageCode.PASS_STEP_LIST_FAIL)");
//	map.put("通过仓库工单处理类型失败", "I18nHolder.format(I18nMessageCode.PROCESS_TYPE_BY_WH_ORDER_FAIL)");
//	map.put("数据源下拉框加载出现异常", "I18nHolder.format(I18nMessageCode.DATSOURCE_DROPDOWN_LOAD_EPT)");
//	map.put("数据源配置名称为空", "I18nHolder.format(I18nMessageCode.DATASOURCE_CONF_NAME_IS_NULL)");
//	map.put("Sql为空", "I18nHolder.format(I18nMessageCode.SQL_IS_NULL)");
//	map.put("无可执行Sql", "I18nHolder.format(I18nMessageCode.NO_SQL_PROCESS)");
//	map.put("查询执行失败", "I18nHolder.format(I18nMessageCode.QUERY_PROCESS_FAIL)");
//	map.put("当前用户没有权限执行, 请联系超级管理员", "I18nHolder.format(I18nMessageCode.CUR_USER_NOT_AUTH_CONCAT_ADMIN)");
//	map.put("xid为空", "I18nHolder.format(I18nMessageCode.XID_IS_NULL)");
//	map.put("不支持批量操作", "I18nHolder.format(I18nMessageCode.NO_SUPPORT_BATCH_OPER)");
//	map.put("executeXANonQuery执行失败", "I18nHolder.format(I18nMessageCode.EXECUTEXANONQUERY_PROCESS_FAIL)");
//	map.put("查询数据错误", "I18nHolder.format(I18nMessageCode.QUERY_DATA_ERROR)");
//	map.put("参数为空,无法过账", "I18nHolder.format(I18nMessageCode.PARAM_IS_NULL_NOT_POST)");
//	map.put("没有可以过账的到货通知单", "I18nHolder.format(I18nMessageCode.NO_DELIVERY_NOTICE_TO_POST)");
//	map.put("批量收货过账任务创建失败", "I18nHolder.format(I18nMessageCode.CREATED_BATCH_POST_TASK_FAIL)");
//	map.put("参数为空,关闭交货单失败", "I18nHolder.format(I18nMessageCode.PARAM_NULL_CLOSE_DELINOTE_FAIL)");
//	map.put("功能未实现", "I18nHolder.format(I18nMessageCode.FUNCTION_NOT_IMPL)");
//	map.put("关闭交货单失败", "I18nHolder.format(I18nMessageCode.CLOSE_DELIVERY_NOTE_FAIL)");
//	map.put("获取打印清单失败", "I18nHolder.format(I18nMessageCode.GET_PRINT_NOTE_FAIL)");
//	map.put("计算失败!", "I18nHolder.format(I18nMessageCode.CALC_FAIL)");
//	map.put("请选择查询方式", "I18nHolder.format(I18nMessageCode.SELECT_QUERY_MODE)");
//	map.put("请输入商家采购单号", "I18nHolder.format(I18nMessageCode.PRINT_MERCHAT_PUR_NUM)");
//	map.put("请选择播种开始时间", "I18nHolder.format(I18nMessageCode.SELECT_SENDING_START_TIME)");
//	map.put("请选择播种结束时间", "I18nHolder.format(I18nMessageCode.SELECT_SENDING_END_TIME)");
//	map.put("播种结束时间需大于播种开始时间", "I18nHolder.format(I18nMessageCode.SEEDING_END_GREATER_THAN_START)");
//	map.put("播种结束时间与开始时间间隔不能超过30天", "I18nHolder.format(I18nMessageCode.SEEDING_END_START_NOT_THIR_DAY)");
//	map.put("播种结束时间与开始时间间隔不能超过7天", "I18nHolder.format(I18nMessageCode.SEEDING_END_START_NOT_SEVEN_DAY)");
//	map.put("物流模式为空", "I18nHolder.format(I18nMessageCode.LOGISTICS_MODE_IS_EMPTY)");
//	map.put("物流模式错误", "I18nHolder.format(I18nMessageCode.LOGISTICS_MODE_IS_ERROR)");
//	map.put("初始化页面异常", "I18nHolder.format(I18nMessageCode.INIT_PAGE_EPT)");
//	map.put("正在后台执行打印和下发", "I18nHolder.format(I18nMessageCode.PRINT_AND_DISTRIB_IN_BACK)");
//	map.put("正在后台执行重新下发", "I18nHolder.format(I18nMessageCode.PERFORM_DISTRIB_IN_BACK)");
//	map.put("阁楼打印打印机配置中没有配置当前客户端ip", "I18nHolder.format(I18nMessageCode.PRINT_MACHINE_NO_CONFIG_IP)");
//	map.put("创建时间从不能为空", "I18nHolder.format(I18nMessageCode.CREATED_TIME_FROM_IS_NOT_NULL)");
//	map.put("创建时间到不能为空", "I18nHolder.format(I18nMessageCode.CREATED_TIME_TO_IS_NOT_NULL)");
//	map.put("周转箱注册成功", "I18nHolder.format(I18nMessageCode.TUR_BOX_REGISTERED_SUCCESSFULLY)");
//	map.put("注册失败", "I18nHolder.format(I18nMessageCode.REGISTER_FAIL)");
//	map.put("传入参数为空", "I18nHolder.format(I18nMessageCode.INCOMING_PARAM_IS_NULL)");
//	map.put("传入的id集合为空", "I18nHolder.format(I18nMessageCode.INCOMING_IDS_IS_NULL)");
//	map.put("正在后台开始执行周转箱拣货标签打印", "I18nHolder.format(I18nMessageCode.PRINT_PICK_TURBOX_LABLE_IN_BACK)");
//	map.put("正在后台开始执行重新下发", "I18nHolder.format(I18nMessageCode.PERFORM_START_DISTRIB_IN_BACK)");
//	map.put("系统异常", "I18nHolder.format(I18nMessageCode.SYSTEM_EPT)");
//	map.put("下发失败", "I18nHolder.format(I18nMessageCode.DISTRIB_FAIL)");
//	map.put("仓库为空", "I18nHolder.format(I18nMessageCode.WH_IS_NULL)");
//	map.put("下发波次为空", "I18nHolder.format(I18nMessageCode.DISTRIB_WAVE_IS_NULL)");
//	map.put("正常", "I18nHolder.format(I18nMessageCode.NORMAL)");
//	map.put("加急", "I18nHolder.format(I18nMessageCode.URGENT)");
//	map.put("小店接口", "I18nHolder.format(I18nMessageCode.SMALL_SHOP_IMPL)");
//	map.put("已下发", "I18nHolder.format(I18nMessageCode.ISSUED)");
//	map.put("未下发", "I18nHolder.format(I18nMessageCode.NOT_DISTRRIBUTED)");
//	map.put("展示列表页失败", "I18nHolder.format(I18nMessageCode.DISPLAY_LIST_PAGE_FAILED)");
//	map.put("作业单元导出失败", "I18nHolder.format(I18nMessageCode.ACTIVITY_EXPORT_FAILED)");
//	map.put("容器码组盘数据不存在", "I18nHolder.format(I18nMessageCode.CONTAINER_CODE_RESET_NOEXIST)");
//	map.put("容器已组盘", "I18nHolder.format(I18nMessageCode.CONTAINER_RESET)");
//	map.put("容器已关闭", "I18nHolder.format(I18nMessageCode.CONTAINER_CLOSE)");
//	map.put("库存不存在", "I18nHolder.format(I18nMessageCode.STOCK_NOEXIST)");
//	map.put("容器编码不存在，请核实", "I18nHolder.format(I18nMessageCode.CONTAINER_CODE_NOEXIST_CHECK)");
//	map.put("不能重复组盘", "I18nHolder.format(I18nMessageCode.DONT_REPEAT_RESET)");
//	map.put("该组盘记录已关闭", "I18nHolder.format(I18nMessageCode.RESET_RECORD_CLOSE)");
//	map.put("非顶级容器码不能修改组盘数量", "I18nHolder.format(I18nMessageCode.NO_TOP_CONTAINER_NOUPDATE_NUM)");
//	map.put("发货组盘失败", "I18nHolder.format(I18nMessageCode.DELIVERY_RESET_FAIL)");
//	map.put("客户编码不存在", "I18nHolder.format(I18nMessageCode.CUSTOMER_CODE_NOEXIT)");
//	map.put("找不到输入的用户", "I18nHolder.format(I18nMessageCode.NOTFIND_ENTER_USER)");
//	map.put("请选择过账客户交货单", "I18nHolder.format(I18nMessageCode.SELECT_POST_ODD_NUM)");
//	map.put("请登录", "I18nHolder.format(I18nMessageCode.PLEASE_LOGIN)");
//	map.put("请勾选记录", "I18nHolder.format(I18nMessageCode.PLEASE_CHECK_RECORD)");
//	map.put("过账失败", "I18nHolder.format(I18nMessageCode.POST_FAIL)");
//	map.put("TU单为空", "I18nHolder.format(I18nMessageCode.TU_ORDER_IS_NULL)");
//	map.put("id数组为空", "I18nHolder.format(I18nMessageCode.ID_ARRAY_IS_NULL)");
//	map.put("获取默认贵品容器类型失败", "I18nHolder.format(I18nMessageCode.GET_VALUABLE_HUCODES_FAIL)");
//	map.put("当前操作仓库为空", "I18nHolder.format(I18nMessageCode.CUR_OPER_WH_IS_NULL)");
//	map.put("当前操作仓位为空", "I18nHolder.format(I18nMessageCode.CUR_OPER_IS_LOCAL_NULL)");
//	map.put("容器码不能为空", "I18nHolder.format(I18nMessageCode.CONTAINER_CODE_IS_NOT_NULL)");
//	map.put("无法获取当前操作用户，请尝试重新登录", "I18nHolder.format(I18nMessageCode.NOT_GET_CUR_USER_AGAIN_LOGIN)");
//	map.put("消息id不能为空", "I18nHolder.format(I18nMessageCode.MESSAGE_ID_IS_NOT_NULL)");
//	map.put("确认异常", "I18nHolder.format(I18nMessageCode.CONFRIM_EPT)");
//	map.put("客户交货单号为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_ODD_NUM_IS_NULL)");
//	map.put("客户交货单ID为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_POST_ORDER_ID_IS_NULL)");
//	map.put("客户交货单ID列表为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_POST_ORDER_ID_LIST_NULL)");
//	map.put("找不到需要关闭的客户订单", "I18nHolder.format(I18nMessageCode.NOTFIND_CLOSE_CUSTOMER_ORDER)");
//	map.put("批量发货过账失败, 参数为空", "I18nHolder.format(I18nMessageCode.BATCH_POST_FAIL_PARAM_NULL)");
//	map.put("批量发货过账任务创建失败", "I18nHolder.format(I18nMessageCode.BATCH_POST_TASK_CREATED_FAIL)");
//	map.put("发货过账失败, 交货单明细列表为空", "I18nHolder.format(I18nMessageCode.POST_FAIL_DELIVERY_DETAIL_NULL)");
//	map.put("发货过账失败, 交货单ID为空", "I18nHolder.format(I18nMessageCode.POST_FAIL_DELIVERY_ID_NULL)");
//	map.put("波次创建中，请稍后查看结果", "I18nHolder.format(I18nMessageCode.WAVE_CREATION_VIEW_RESULT_LATE)");
//	map.put("客户交货单明细ID为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_DEVLI_DETAILID_IS_NULL)");
//	map.put("要打印的客户交货单为空", "I18nHolder.format(I18nMessageCode.PRINT_CUS_POST_ORDER_IS_NULL)");
//	map.put("获取退货汇总单打印信息异常", "I18nHolder.format(I18nMessageCode.GET_RETURN_COLLECT_PRINTINFO_EPT)");
//	map.put("找不到要创建任务的外向交货单行项目", "I18nHolder.format(I18nMessageCode.NOTFIND_CREATETASK_POST_ITEM)");
//	map.put("创建任务展示页面发生异常", "I18nHolder.format(I18nMessageCode.CREATE_TASK_DISPLAY_EPT)");
//	map.put("客户交货单不能为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_POST_ORDER_NOT_NULL)");
//	map.put("查询跳转类型失败", "I18nHolder.format(I18nMessageCode.QUERY_JUMP_TYPE_FAIL)");
//	map.put("入参数据不能为空", "I18nHolder.format(I18nMessageCode.GINSENG_NOT_NULL)");
//	map.put("客户交货单行项不能为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_POST_ITEM_NOT_NULL)");
//	map.put("分配数量为空", "I18nHolder.format(I18nMessageCode.AAU_NUM_IS_EMPTY)");
//	map.put("分配数量不能小于0", "I18nHolder.format(I18nMessageCode.AAU_NUM_NOT_LT_ZERO)");
//	map.put("客户交货单行项目创建拣配失败", "I18nHolder.format(I18nMessageCode.CUS_POST_ITEM_CREATEPICK_FAIL)");
//	map.put("查询数据为空", "I18nHolder.format(I18nMessageCode.QUERY_DATA_NULL)");
//	map.put("入参data为空", "I18nHolder.format(I18nMessageCode.GINSENG_DATA_NULL)");
//	map.put("请选择交货过账单", "I18nHolder.format(I18nMessageCode.PLEASE_CHOOSE_POST_ORDER)");
//	map.put("发送打印成功", "I18nHolder.format(I18nMessageCode.SEND_PRINT_SUCCESS)");
//	map.put("查询打印数据异常", "I18nHolder.format(I18nMessageCode.QUERY_PRINT_DATA_EPT)");
//	map.put("直流效绩", "I18nHolder.format(I18nMessageCode.DC_PERFORMANCE)");
//	map.put("确认开始时间为空", "I18nHolder.format(I18nMessageCode.CONFIRM_START_TIME_NULL)");
//	map.put("确认截止时间为空", "I18nHolder.format(I18nMessageCode.CONFIRM_END_TIME_NULL)");
//	map.put("工单处理类型和存储类型不能都为空", "I18nHolder.format(I18nMessageCode.ORDER_STORAGE_TYPE_NOT_NULL)");
//	map.put("数据id为空", "I18nHolder.format(I18nMessageCode.DATA_ID_NULL)");
//	map.put("仓位编码为空", "I18nHolder.format(I18nMessageCode.BIN_CODE_NULL)");
//	map.put("不存在id对应的数据", "I18nHolder.format(I18nMessageCode.NOTEXIT_ID_DATA)");
//	map.put("不存在仓位", "I18nHolder.format(I18nMessageCode.NOTEXIT_BIN)");
//	map.put("仓位对应的存储类型不存在", "I18nHolder.format(I18nMessageCode.BIN_STORAGE_TYPE_NOEXIT)");
//	map.put("非提总区仓位不允许修改", "I18nHolder.format(I18nMessageCode.NOT_DRAW_TOTAL_BIN_NOT_MODIFY)");
//	map.put("包材类型为空", "I18nHolder.format(I18nMessageCode.HU_TYPE_NULL)");
//	map.put("任务id为空", "I18nHolder.format(I18nMessageCode.TASK_ID_NULL)");
//	map.put("修改成功", "I18nHolder.format(I18nMessageCode.MODIFY_SUCCESS)");
//	map.put("查询已确认任务时，工单号、商品编码、客户和波次不能同时为空", "I18nHolder.format(I18nMessageCode.TASK_CODE_ORDER_WAVE_CUS_NOTNULL)");
//	map.put("确认起始时间不能为空", "I18nHolder.format(I18nMessageCode.CONFIRM_START_TIME_NOT_NULL)");
//	map.put("确认结束时间不能为空", "I18nHolder.format(I18nMessageCode.CONFIRM_END_TIME_NOT_NULL)");
//	map.put("确认时间间隔不能大于7天", "I18nHolder.format(I18nMessageCode.CONFIRM_TIME_BLANK_NOT_SEVEN_DAY)");
//	map.put("根据传入的打印机配置未找到对应打印机", "I18nHolder.format(I18nMessageCode.PRINT_CONFIG_NOTFIND_MACHINE)");
//	map.put("连接至打印机失败，无法打印", "I18nHolder.format(I18nMessageCode.CONNETCT_PRINT_MACHINE_FAIL)");
//	map.put("打印失败", "I18nHolder.format(I18nMessageCode.PRINT_FAIL)");
//	map.put("国条不存在", "I18nHolder.format(I18nMessageCode.EANS_NOEXIT)");
//	map.put("源存储类型不存在", "I18nHolder.format(I18nMessageCode.SOURCE_STORAGE_TYPE_NOEXIT)");
//	map.put("拥有者不存在", "I18nHolder.format(I18nMessageCode.OWNER_NOEXIT)");
//	map.put("请选择确认工单", "I18nHolder.format(I18nMessageCode.SELECT_CONFIRM_ORDER)");
//	map.put("请选择取消工单", "I18nHolder.format(I18nMessageCode.SELECT_CANCLE_ORDER)");
//	map.put("请选择订单行项", "I18nHolder.format(I18nMessageCode.SELECT_ORDER_ITEM)");
//	map.put("冲销异常", "I18nHolder.format(I18nMessageCode.WRITE_OFF_EPT)");
//	map.put("工单处理类型为空", "I18nHolder.format(I18nMessageCode.WORK_TYPE_IS_NULL)");
//	map.put("请选择锁定工单", "I18nHolder.format(I18nMessageCode.PLEASE_LOCK_ORDER)");
//	map.put("请选择解锁工单", "I18nHolder.format(I18nMessageCode.PLEASE_SELECT_UNLOCK_JOB)");
//	map.put("源存储区域不存在", "I18nHolder.format(I18nMessageCode.SOURCE_AREA_NOEXIT)");
//	map.put("解除工单占用状态成功", "I18nHolder.format(I18nMessageCode.REMOVE_ORDER_EPLOYEE_SUCCESS)");
//	map.put("更新加急拣配标识成功", "I18nHolder.format(I18nMessageCode.UPDATE_PICK_TAG_SUCCESS)");
//	map.put("更新加急拣配标识异常", "I18nHolder.format(I18nMessageCode.UPDATE_PICK_TAG_EPT)");
//	map.put("请选择锁定波次", "I18nHolder.format(I18nMessageCode.SELECT_LOCK_WAVE)");
//	map.put("请选择解锁波次", "I18nHolder.format(I18nMessageCode.PLEASE_UNLOCK_WAVE)");
//	map.put("波次id为空", "I18nHolder.format(I18nMessageCode.WAVE_ID_IS_NULL)");
//	map.put("请选择合并波次", "I18nHolder.format(I18nMessageCode.PLEASE_CHOOSE_MERGE_WAVE)");
//	map.put("请选择汇总波次", "I18nHolder.format(I18nMessageCode.PLEASE_MERGE_WAVE)");
//	map.put("请选择释放波次", "I18nHolder.format(I18nMessageCode.SELECT_RELEASE_WAVE)");
//	map.put("释放方式为空", "I18nHolder.format(I18nMessageCode.RELEASE_METH_IS_NULL)");
//	map.put("请设置小车号", "I18nHolder.format(I18nMessageCode.PLEASE_SETTING_CARTNUM)");
//	map.put("请选择波次", "I18nHolder.format(I18nMessageCode.PLEASE_SELECT_WAVE)");
//	map.put("波次不存在", "I18nHolder.format(I18nMessageCode.WAVE_NOEXIT)");
//	map.put("无拆零拆分波次", "I18nHolder.format(I18nMessageCode.NO_SPLIT_WAVE)");
//	map.put("拆零波次与非拆零波次不允许混合处理", "I18nHolder.format(I18nMessageCode.SPLIT_NO_WAVE_MIXED_TREAT)");
//	map.put("商品不存在", "I18nHolder.format(I18nMessageCode.PRODUCT_NOEXIT)");
//	map.put("请选择拆分波次行项目", "I18nHolder.format(I18nMessageCode.PLEASE_SPLIT_WAVE_ITEM)");
//	map.put("请选择重分波次行项目", "I18nHolder.format(I18nMessageCode.PLEASE_RESPLIT_WAVE_ITEM)");
//	map.put("请选择输入目标波次", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_TARGET_WAVE)");
//	map.put("数据id集合为空", "I18nHolder.format(I18nMessageCode.IDS_COLLECTION_IS_NULL)");
//	map.put("二次拣配标识为空", "I18nHolder.format(I18nMessageCode.SECOND_PICK_TAG_IS_NULL)");
//	map.put("更新二次拣配标识失败", "I18nHolder.format(I18nMessageCode.UPDATE_SECOND_PICK_TAG_FAIL)");
//	map.put("波次行项目导出失败", "I18nHolder.format(I18nMessageCode.WAVE_ITEM_EXPORT_FAIL)");
//	map.put("Po单暂不支持新增!", "I18nHolder.format(I18nMessageCode.PO_ORDER_SUPP_ADD)");
//	map.put("Po单暂不支持更新!", "I18nHolder.format(I18nMessageCode.PO_ORDER_SUPP_UPDATE)");
//	map.put("取消出现异常", "I18nHolder.format(I18nMessageCode.CANCLE_EPT)");
//	map.put("修改出现异常", "I18nHolder.format(I18nMessageCode.MODIFY_EPT)");
//	map.put("修改行项目物流模式", "I18nHolder.format(I18nMessageCode.MODIFY_ITEM_LOGISTICS_MODEL)");
//	map.put("后台批量修改行项目物流模式", "I18nHolder.format(I18nMessageCode.BATCH_MODI_LOGI_ITEM_IN_BACK)");
//	map.put("批量收货过账失败, 参数为空", "I18nHolder.format(I18nMessageCode.BATCH_RECI_POST_FAIL_PARAM_NULL)");
//	map.put("批量收货过账任务query_product_ept", "I18nHolder.format(I18nMessageCode.BATCH_RECI_POST_TASK_CREATE_FAIL)");
//	map.put("批量获取打印信息失败, 参数为空", "I18nHolder.format(I18nMessageCode.BATCH_PRINTINFO_FAIL_PARAM_NULL)");
//	map.put("批量获取打印信息失败", "I18nHolder.format(I18nMessageCode.BATCH_PRINTINFO_FAIL)");
//	map.put("到货通知单ID不能为空!", "I18nHolder.format(I18nMessageCode.ASN_ID_NOT_NULL)");
//	map.put("物流类型不能为空!", "I18nHolder.format(I18nMessageCode.LOGISTICSTYPE_NOT_NULL)");
//	map.put("已进入收货阶段，不可修改。", "I18nHolder.format(I18nMessageCode.RECEIVING_STAGE_NOT_MODIFY)");
//	map.put("查询商品异常", "I18nHolder.format(I18nMessageCode.QUERY_PRODUCT_EPT)");
//	map.put("到货通知单行项目批量上架参数错误", "I18nHolder.format(I18nMessageCode.ASN_ITEM_BATCH_PUT_PARAM_ERROR)");
//	map.put("到货通知单行项目批量上架确认参数错误", "I18nHolder.format(I18nMessageCode.ASN_ITEM_BATCH_CONFPARAM_ERROR)");
//	map.put("到货通知单行项目批量上架确认异常", "I18nHolder.format(I18nMessageCode.ASN_ITEM_BATCH_PUT_CONFIRM_EPT)");
//	map.put("批量获取收货组盘信息参数错误", "I18nHolder.format(I18nMessageCode.BATCH_RECI_RESETINFO_PARAM_ERROR)");
//	map.put("批量收货组盘参数错误", "I18nHolder.format(I18nMessageCode.BATCH_RECI_RESET_PARAM_ERROR)");
//	map.put("批量收货组盘异常", "I18nHolder.format(I18nMessageCode.BATCH_RECI_RESET_EPT)");
//	map.put("获取冲销列表失败", "I18nHolder.format(I18nMessageCode.GET_WRITE_OFF_LIST_FAIL)");
//	map.put("批量冲销参数错误", "I18nHolder.format(I18nMessageCode.BATCH_WRITE_OFF_PARAM_ERROR)");
//	map.put("批量冲销失败", "I18nHolder.format(I18nMessageCode.BATCH_WRITE_OFF_FAIL)");
//	map.put("采购单号验证失败!", "I18nHolder.format(I18nMessageCode.PURS_ORDER_CHECK_FAIL)");
//	map.put("客户规模为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_SCALE_NULL)");
//	map.put("采购单号必输", "I18nHolder.format(I18nMessageCode.PURS_NUM_MUST_ENTER)");
//	map.put("没找到po单", "I18nHolder.format(I18nMessageCode.NOFIND_PO_ORDER)");
//	map.put("可用的托盘码!", "I18nHolder.format(I18nMessageCode.ALIVE_TRAY_CODE)");
//	map.put("该托盘码已被占用", "I18nHolder.format(I18nMessageCode.TRAY_CODE_OCCUPY)");
//	map.put("校验托盘码出现异常", "I18nHolder.format(I18nMessageCode.CHECK_TRAY_CODE_EPT)");
//	map.put("仓位参数错误", "I18nHolder.format(I18nMessageCode.BIN_PARAM_ERROR)");
//	map.put("校验仓位编码异常", "I18nHolder.format(I18nMessageCode.CHECK_BIN_CODE_EPT)");
//	map.put("商品列表查询失败", "I18nHolder.format(I18nMessageCode.PRODUCT_QUERY_LIST_FAIL)");
//	map.put("商品信息查询失败", "I18nHolder.format(I18nMessageCode.PRODUCT_INFO_QUERY_FAIL)");
//	map.put("查无商品", "I18nHolder.format(I18nMessageCode.QUERY_NO_PRODUCT)");
//	map.put("查无授权方", "I18nHolder.format(I18nMessageCode.QUERY_NO_EP)");
//	map.put("校验临期收货失败", "I18nHolder.format(I18nMessageCode.CHECK_IMPEND_RECI_FAIL)");
//	map.put("参数id为空或不合规", "I18nHolder.format(I18nMessageCode.PARAM_ID_NULL)");
//	map.put("请选择需要确认的任务", "I18nHolder.format(I18nMessageCode.PLEASE_SELECT_NEED_CONFIRM_TASK)");
//	map.put("批量确认退货上架任务成功", "I18nHolder.format(I18nMessageCode.BATCH_CONF_RET_PUT_TASK_SUCCESS)");
//	map.put("标件商品不能进行一步直流", "I18nHolder.format(I18nMessageCode.J_NUT_PRODUCT_NOT_ZL)");
//	map.put("收货数量不能为0get_remo", "I18nHolder.format(I18nMessageCode.RECI_NUM_NOT_ZERO)");
//	map.put("批量一步直流上架参数错误", "I18nHolder.format(I18nMessageCode.BATCH_STEP_ZL_PUT_PARAM_ERROR)");
//	map.put("最大允许勾选500条", "I18nHolder.format(I18nMessageCode.ALLOW_FIVE_HUNDRED)");
//	map.put("直流一步上架操作成功", "I18nHolder.format(I18nMessageCode.ZL_STEP_PUT_SUCESS)");
//	map.put("标件收货数量或重量有误", "I18nHolder.format(I18nMessageCode.J_NUT_RECI_NUM_OR_WEIGHT_ERROR)");
//	map.put("标件收货包材类型有误", "I18nHolder.format(I18nMessageCode.J_NUT_RECI_STUFF_TYPE_ERROR)");
//	map.put("没有找到商家采购单源商品单位", "I18nHolder.format(I18nMessageCode.NOTFIND_MER_PURS_PRODUCT_UNIT)");
//	map.put("创建收货组盘任务失败", "I18nHolder.format(I18nMessageCode.CREATE_RECI_RESET_TASK_FAIL)");
//	map.put("托盘码不能为空", "I18nHolder.format(I18nMessageCode.TRAY_CODE_IS_NOT_NULL)");
//	map.put("托盘码不允许出现小写字母", "I18nHolder.format(I18nMessageCode.TRACODE_NOT_ALLOW_LOW_LETTER)");
//	map.put("无法确定当前正在处理的仓库", "I18nHolder.format(I18nMessageCode.NOT_CONFIRM_CUR_WH)");
//	map.put("创建上架任务工单失败", "I18nHolder.format(I18nMessageCode.CREATE_PUT_TASK_ORDER_FAIL)");
//	map.put("获取上架任务工单失败", "I18nHolder.format(I18nMessageCode.GET_PUTA_TASK_ORDER_FAIL)");
//	map.put("仓位码不能为空", "I18nHolder.format(I18nMessageCode.BIN_CODE_NOT_NULL)");
//	map.put("任务id不能为空", "I18nHolder.format(I18nMessageCode.TASK_ID_NOT_NULL)");
//	map.put("仓位编码不存在", "I18nHolder.format(I18nMessageCode.BIN_CODE_NOEXIT)");
//	map.put("仓位校验失败", "I18nHolder.format(I18nMessageCode.BIN_CHECK_FAIL)");
//	map.put("校验入库上架仓位失败", "I18nHolder.format(I18nMessageCode.CHECK_PUT_BIN_FAIL)");
//	map.put("获取推荐仓位失败", "I18nHolder.format(I18nMessageCode.GET_RECOMMEND_BIN_FAIL)");
//	map.put("请输入正确仓位编码", "I18nHolder.format(I18nMessageCode.ENTER_TRUE_BIN_CODE)");
//	map.put("上架任务确认完成成功!", "I18nHolder.format(I18nMessageCode.PUTA_TASK_CONFIRM_SUCCESS_COMP)");
//	map.put("上架任务确认失败", "I18nHolder.format(I18nMessageCode.PUT_TASK_CONFIRM_FAIL)");
//	map.put("校验失败!", "I18nHolder.format(I18nMessageCode.CHECK_FAIL)");
//	map.put("收货人请设置签字模板!", "I18nHolder.format(I18nMessageCode.RECI_OPER_PLEASE_SET_SIGN_TEMP)");
//	map.put("创建收货过账任务失败, ID", "I18nHolder.format(I18nMessageCode.CREAT_RECI_ASN_TASK_FAIL_ID)");
//	map.put("收货过账任务创建失败", "I18nHolder.format(I18nMessageCode.RECI_ASN_TASK_CREATE_FAIL)");
//	map.put("获取收货过账列表失败!!", "I18nHolder.format(I18nMessageCode.GET_RECI_ASN_LIST_FAIL)");
//	map.put("获取待上架任务列表失败!!", "I18nHolder.format(I18nMessageCode.GET_PUT_TASK_LIST_FAIL)");
//	map.put("待上架任务导出失败!", "I18nHolder.format(I18nMessageCode.WAIT_PUT_TASK_EXPORT_FAIL)");
//	map.put("epId为空", "I18nHolder.format(I18nMessageCode.EPID_NULL)");
//	map.put("批量一步退货上架参数错误", "I18nHolder.format(I18nMessageCode.BATCH_STEP_RETURN_PUT_PARAM_FAIL)");
//	map.put("该仓库未配置一步退货全局开关", "I18nHolder.format(I18nMessageCode.CUR_WH_CONF_STEP_RETURN_BUTTON)");
//	map.put("该仓库不允许进行一步退货上架", "I18nHolder.format(I18nMessageCode.CUR_WH_NOT_ALLOW_STEP_RETURN_PUT)");
//	map.put("获取到货通知单明细失败", "I18nHolder.format(I18nMessageCode.GET_ARRVAL_NOTIFY_DETAIL_FAIL)");
//	map.put("到货通知单明细不存在", "I18nHolder.format(I18nMessageCode.ARRVAL_NOTIFY_DETAIL_NOEXIT)");
//	map.put("获取到货通知单失败", "I18nHolder.format(I18nMessageCode.GET_ARRVAL_NOTIFY_FAIL)");
//	map.put("到货通知单不存在", "I18nHolder.format(I18nMessageCode.ARRAVAL_NOTIFY_NOEXIT)");
//	map.put("一步退货上架正在进行,结果稍后通知", "I18nHolder.format(I18nMessageCode.STEP_RETURN_PUT_GOON_NOTI_LATER)");
//	map.put("驳回审批失败", "I18nHolder.format(I18nMessageCode.REJECT_APPROVAL_FAIL)");
//	map.put("审批记录id为空", "I18nHolder.format(I18nMessageCode.APPROVAL_RECORD_ID_NULL)");
//	map.put("创建报损任务失败", "I18nHolder.format(I18nMessageCode.CREATE_LOSS_TASK_FAIL)");
//	map.put("不存在该仓位、条码或商品编码", "I18nHolder.format(I18nMessageCode.NOEXIT_BIN_EAN_PRODUCT_CODE)");
//	map.put("条码或商品编码为空", "I18nHolder.format(I18nMessageCode.EAN_OR_PRODUCTCODE_NULL)");
//	map.put("仓库中没有条码对应的商品", "I18nHolder.format(I18nMessageCode.WH_NO_CORR_EAN_PRODUCT)");
//	map.put("该商品编码或条码不存在", "I18nHolder.format(I18nMessageCode.PRODUCTCODE_OR_EAN_NOEXIT)");
//	map.put("提交成功", "I18nHolder.format(I18nMessageCode.COMMIT_SUCCESS)");
//	map.put("创建库存类型调整任务失败", "I18nHolder.format(I18nMessageCode.CREAT_STORAGE_TYPE_TASK_FAIL)");
//	map.put("移转请求已发送，请注意查收消息", "I18nHolder.format(I18nMessageCode.MOVE_REQUEST_SEND_CAREFUL)");
//	map.put("按处理单位创建移仓任务失败", "I18nHolder.format(I18nMessageCode.DEAL_UNIT_CREAT_MOVE_TASK_FAIL)");
//	map.put("初始化转仓绩效查询失败", "I18nHolder.format(I18nMessageCode.INIT_MOVE_PERF_QUERY_FAIL)");
//	map.put("创建任务异常", "I18nHolder.format(I18nMessageCode.CREATE_TASK_EPT)");
//	map.put("创建移仓任务失败", "I18nHolder.format(I18nMessageCode.CREATE_MOVE_TASK_FAIL)");
//	map.put("根据库存获取重量失败", "I18nHolder.format(I18nMessageCode.GET_WEIGHT_BY_STOCK_FAIL)");
//	map.put("获取标件信息失败", "I18nHolder.format(I18nMessageCode.GET_J_NUT_INFO_FAIL)");
//	map.put("根据仓库编码查询仓库为空", "I18nHolder.format(I18nMessageCode.GET_WH_BY_CODE_IS_NULL)");
//	map.put("根据授权方编码查询授权方数据为空", "I18nHolder.format(I18nMessageCode.GET_EP_BY_CODE_IS_NULL)");
//	map.put("商品包装不存在", "I18nHolder.format(I18nMessageCode.PRODUCT_PACKAGE_NOEXIT)");
//	map.put("商品基本包装不存在", "I18nHolder.format(I18nMessageCode.PRODUCT_BASE_PACKAGE_NOEXIT)");
//	map.put("存储类型查询异常", "I18nHolder.format(I18nMessageCode.STORAGE_TYPE_QUERY_EPT)");
//	map.put("未找到加工区的存储类型配置", "I18nHolder.format(I18nMessageCode.NOTFIND_STORAGE_TYPE_CONF)");
//	map.put("提交创建的内容为空", "I18nHolder.format(I18nMessageCode.COMMIT_CREATE_CONTENT_IS_NULL)");
//	map.put("创建异常", "I18nHolder.format(I18nMessageCode.CREATE_EPT)");
//	map.put("创建成功", "I18nHolder.format(I18nMessageCode.CREATE_SUCCESS)");
//	map.put("id集合为空", "I18nHolder.format(I18nMessageCode.ID_CONLLECTION_IS_NULL)");
//	map.put("确认工单失败", "I18nHolder.format(I18nMessageCode.CONFIRM_WORKORDER_FAIL)");
//	map.put("取消工单失败", "I18nHolder.format(I18nMessageCode.CANCLE_WORKORDER_FAIL)");
//	map.put("未选择任何行项目", "I18nHolder.format(I18nMessageCode.NO_SELECT_ANY_ITEM)");
//	map.put("选中的记录不是组件商品", "I18nHolder.format(I18nMessageCode.SELECT_RECORD_NOT_ASSBLEM_PROD)");
//	map.put("不支持多个仓库一起创建", "I18nHolder.format(I18nMessageCode.NO_SUPPORT_MULT_WH_CREATE)");
//	map.put("不支持多个授权方一起创建", "I18nHolder.format(I18nMessageCode.NO_SUPPORT_MULT_EP_CREATE)");
//	map.put("源仓位不存在", "I18nHolder.format(I18nMessageCode.SOURCE_BIN_NOEXIT)");
//	map.put("源仓位被冻结", "I18nHolder.format(I18nMessageCode.SOURCE_BIN_FROZEN)");
//	map.put("领用数量不能为空", "I18nHolder.format(I18nMessageCode.USE_NUM_NOT_NULL)");
//	map.put("源仓位库存不足", "I18nHolder.format(I18nMessageCode.SOURCE_BIN_SOTCK_NOTENOUGH)");
//	map.put("归集规则全局配置表未维护任务类型为分割转码配置", "I18nHolder.format(I18nMessageCode.COLLECT_RULE_CONF_TASK_SPL_CONF)");
//	map.put("归集规则全局配置表分割转码任务类型未配置默认归集规则", "I18nHolder.format(I18nMessageCode.COLLECT_RULE_CONF_SPLIT_TASK_DEF)");
//	map.put("商品包装主数据不存在", "I18nHolder.format(I18nMessageCode.PRODUCTPACKAGE_MASTER_NOEXIT)");
//	map.put("商品包装基本单位不存在", "I18nHolder.format(I18nMessageCode.PRODUCT_PACKAGE_BASE_UNIT_NOEXIT)");
//	map.put("确认任务失败", "I18nHolder.format(I18nMessageCode.CONFIRM_TASK_FAIL)");
//	map.put("校验整板失败", "I18nHolder.format(I18nMessageCode.CHECK_ALL_PLATE_FAIL)");
//	map.put("查询指定仓位任务失败", "I18nHolder.format(I18nMessageCode.QUERY_APPOINTBIN_TASK_FAIL)");
//	map.put("指定仓位补货失败", "I18nHolder.format(I18nMessageCode.APPOINT_BIN_REPLE_FAIL)");
//	map.put("库存id数组为空", "I18nHolder.format(I18nMessageCode.STOCK_ID_ARRAY_NULL)");
//	map.put("id为空", "I18nHolder.format(I18nMessageCode.ID_NULL)");
//	map.put("获取质保期数据失败", "I18nHolder.format(I18nMessageCode.GET_QUALITYTIME_DATA_FAIL)");
//	map.put("仓库id参数为空", "I18nHolder.format(I18nMessageCode.WHID_PARAM_NULL)");
//	map.put("存储类型id和通道不能同时为空", "I18nHolder.format(I18nMessageCode.STORAGETYPEID_PASS_NOT_NULL)");
//	map.put("仓位编码参数为空", "I18nHolder.format(I18nMessageCode.BIN_CODE_PARAM_NOT_NULL)");
//	map.put("待更正日期为空", "I18nHolder.format(I18nMessageCode.TOBE_CORRECTE_TIME_NULL)");
//	map.put("请传任务id", "I18nHolder.format(I18nMessageCode.PLEASE_TRANS_TASKID)");
//	map.put("进入报溢添加操作页失败", "I18nHolder.format(I18nMessageCode.ENTER_LOSS_ADD_OPER_FAIL)");
//	map.put("仓库作业工单归集规则未维护目标仓位", "I18nHolder.format(I18nMessageCode.WH_WORKORDER_COLL_RULE_NOTBIN)");
//	map.put("保质期核检记录不存在", "I18nHolder.format(I18nMessageCode.QUALITYTIME_CHECK_RECORDNOEXIT)");
//	map.put("[{00}]保质期核检已确认，无法取消", "I18nHolder.format(I18nMessageCode.QUALITYTIME_CONFIRM_NOTCANCLE)");
//	map.put("锁定任务失败", "I18nHolder.format(I18nMessageCode.LOCK_TASK_FAIL)");
//	map.put("解锁任务失败", "I18nHolder.format(I18nMessageCode.UNLOCK_TASK_FAIL)");
//	map.put("存储类型编码为空", "I18nHolder.format(I18nMessageCode.STORAGETYPE_CODE_IS_NULL)");
//	map.put("解占任务失败", "I18nHolder.format(I18nMessageCode.OCCUPY_TASK_FAIL)");
//	map.put("锁定工单失败", "I18nHolder.format(I18nMessageCode.LOCK_WORKORDER_FAIL)");
//	map.put("解锁工单失败", "I18nHolder.format(I18nMessageCode.UNLOCK_WORKORDER_FAIL)");
//	map.put("图片文件类型无法确认", "I18nHolder.format(I18nMessageCode.IMG_FILE_TYPE_NOT_CONFIRM)");
//	map.put("加载跟应用日志有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_APP_LOG_MASTER_SOURCE_FAIL)");
//	map.put("日志查询操作失败", "I18nHolder.format(I18nMessageCode.LOG_QUERY_OPER_FAIL)");
//	map.put("获取数据导出任务信息失败", "I18nHolder.format(I18nMessageCode.GET_EXPORT_TASK_INFO_FAIL)");
//	map.put("加载跟导出任务相关的下拉框数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_EXPORT_TASK_DROP_SOUR_FAIL)");
//	map.put("加载跟数据导入相关的下拉框数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_IMPORT_DROP_SOUR_FAIL)");
//	map.put("获取导入结果日志数据失败", "I18nHolder.format(I18nMessageCode.GET_IMPORT_RESULT_LOG_DATA_FAIL)");
//	map.put("没有可下载的导入结果日志数据", "I18nHolder.format(I18nMessageCode.NO_DOWNLOAD_IMPORT_RESULT_LOG)");
//	map.put("重发消息成功", "I18nHolder.format(I18nMessageCode.REPEAT_MESSAGE_SUCCESS)");
//	map.put("重试失败", "I18nHolder.format(I18nMessageCode.REPEAT_FAIL)");
//	map.put("外部消息推送日志查询失败", "I18nHolder.format(I18nMessageCode.OUT_MSG_PUSH_LOG_QUERY_FAIL)");
//	map.put("外部消息推送日志查看详情失败", "I18nHolder.format(I18nMessageCode.OUT_MSG_PUSH_LOG_VIEW_FAIL)");
//	map.put("外部消息接受日志查询失败", "I18nHolder.format(I18nMessageCode.OUT_MSG_RECI_LOG_QUERY_FAIL)");
//	map.put("外部消息接受日志查看详情失败", "I18nHolder.format(I18nMessageCode.OUT_MSG_RECI_LOG_DETAIL_FAIL)");
//	map.put("加载跟消息查询相关的下拉框数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_MSG_QUERY_DROP_SOUR_FAIL)");
//	map.put("查询详情失败", "I18nHolder.format(I18nMessageCode.QUERY_DETAIL_FAIL)");
//	map.put("加载跟Restful调用日志查询相关的下拉框数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_RESTFUL_LOG_DROP_SOUR_FAIL)");
//	map.put("波次数据导出", "I18nHolder.format(I18nMessageCode.WAVE_DATA_EXPORT)");
//	map.put("根据code查询客户失败", "I18nHolder.format(I18nMessageCode.QUERY_CUS_BY_CODE_FAIL)");
//	map.put("请输入客户", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_CUS)");
//	map.put("保存参数异常", "I18nHolder.format(I18nMessageCode.SAVE_PARAM_EPT)");
//	map.put("参数异常", "I18nHolder.format(I18nMessageCode.PARAM_EPT)");
//	map.put("批量更新操作失败", "I18nHolder.format(I18nMessageCode.BATCH_UPDATE_OPER_FAIL)");
//	map.put("加载跟授权方有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_EP_SOURCE_FAIL)");
//	map.put("商家商品信息新增出现异常", "I18nHolder.format(I18nMessageCode.MERCHAT_PRODUCT_ADD_EPT)");
//	map.put("获取商家商品信息失败", "I18nHolder.format(I18nMessageCode.GET_MERCAHT_PRODUCT_FAIL)");
//	map.put("新生成仓库商品重失败", "I18nHolder.format(I18nMessageCode.NEW_CREATE_WH_PRODUCT_FAIL)");
//	map.put("商家id为空", "I18nHolder.format(I18nMessageCode.MERCAHT_ID_IS_NULL)");
//	map.put("授权方id为空", "I18nHolder.format(I18nMessageCode.EP_ID_IS_NULL)");
//	map.put("重新生成仓库商品失败", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_PRODUCT_FAIL)");
//	map.put("商家商品信息更新失败", "I18nHolder.format(I18nMessageCode.MERCHAT_PRODUCT_UPDATE_FAIL)");
//	map.put("商家商品信息查询出现异常", "I18nHolder.format(I18nMessageCode.MERCHAT_PRODUCT_QUERY_FAIL)");
//	map.put("商家为空", "I18nHolder.format(I18nMessageCode.MERCHAT_NULL)");
//	map.put("商家商品信息删除操作失败", "I18nHolder.format(I18nMessageCode.MERCHAT_PRODUCT_DEL_FAIL)");
//	map.put("商家商品分类查询失败", "I18nHolder.format(I18nMessageCode.MERCHAT_PRODUCT_CAT_QUERY_FAIL)");
//	map.put("查找商家商品包装失败", "I18nHolder.format(I18nMessageCode.QUERY_MER_PRODUCT_PACKAGE_FAIL)");
//	map.put("重新生成仓库商品包装出现异常", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_PRO_PACK_EPT)");
//	map.put("重新生成仓库商品包装失败", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_PRO_PACK_FAIL)");
//	map.put("商家商品信息查询操作失败", "I18nHolder.format(I18nMessageCode.MER_PRO_QUERY_OPER_FAIL)");
//	map.put("加载跟商品类目有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_PRO_CAT_MAS_SOUR_FAIL)");
//	map.put("加载跟包装规格相关的下拉框数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_PACK_SPECI_DROP_SOUR_FAIL)");
//	map.put("bom商品更新失败!", "I18nHolder.format(I18nMessageCode.BOM_PRO_UPD_FAIL)");
//	map.put("查询bom商品失败!", "I18nHolder.format(I18nMessageCode.BOM_PRO_QUE_FAILBOM)");
//	map.put("加载跟产品有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_GOOD_MAS_SOUR_FAIL)");
//	map.put("查询关联当前仓库的仓库组和标识数据源失败", "I18nHolder.format(I18nMessageCode.QUERY_RELA_WH_GROUP_TAG_SOU_FAIL)");
//	map.put("加载跟产品单位有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_GOOD_UNIT_MAS_SOUR_FAIL)");
//	map.put("修复ean失败", "I18nHolder.format(I18nMessageCode.REPAIR_EAN_FAIL)");
//	map.put("修复成功", "I18nHolder.format(I18nMessageCode.REPAIR_SUCCESS)");
//	map.put("查询关联当前仓库和授权方的商品数据源失败", "I18nHolder.format(I18nMessageCode.QUE_RELA_CUR_WH_EP_SOUR_FAIL)");
//	map.put("根据出库控制条件获取库存包装单位模式失败", "I18nHolder.format(I18nMessageCode.GI_CONT_GET_PACK_UNIT_MODEL_FAIL)");
//	map.put("[请勾选记录RF维护商品主数据]通过仓库Id和商品SKU/EAN查询商品信息异常",
//		"I18nHolder.format(I18nMessageCode.QUE_PRO_SUK_BY_WHID_FAIL)");
//	map.put("[RF维护商品主数据]通过仓库Id, 授权方Id和商品SKU/EAN查询商品信息异常",
//		"I18nHolder.format(I18nMessageCode.QUE_PRO_SKU_BY_WHID_FAIL)");
//	map.put("[RF维护商品主数据]通过仓库Id, 授权方Id和商品SKU/EAN查询商品信息异常",
//		"I18nHolder.format(I18nMessageCode.QUE_PRO_SUK_BY_WHID_EP_FAIL)");
//	map.put("商品存储类型数据导出", "I18nHolder.format(I18nMessageCode.PRO_STOR_TYPE_EXPORT)");
//	map.put("查询关联当前仓库的存储类型据源失败", "I18nHolder.format(I18nMessageCode.QUE_RELA_CUR_WH_STOR_SOUR_FAIL)");
//	map.put("商品编码填写错误", "I18nHolder.format(I18nMessageCode.PRO_CODE_FILL_ERROR)");
//	map.put("仓位填写错误", "I18nHolder.format(I18nMessageCode.BIN_FILL_ERROR)");
//	map.put("标件不存在", "I18nHolder.format(I18nMessageCode.J_NUT_NOEXIT)");
//	map.put("该仓位上还有库存，不允许删除", "I18nHolder.format(I18nMessageCode.CUR_BIN_HAVE_STOCK_NOTALLOW_DEL)");
//	map.put("查询商品包装数据为空", "I18nHolder.format(I18nMessageCode.QUE_PRO_PACK_IS_NULL)");
//	map.put("查询商品包装单位异常", "I18nHolder.format(I18nMessageCode.QUE_PRO_PACK_EPT)");
//	map.put("所选仓库异常", "I18nHolder.format(I18nMessageCode.CHOICE_WH_EPT)");
//	map.put("加载跟仓库控制条件有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_WH_CONTROL_SOUR_FAIL)");
//	map.put("加载跟标识有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_TAG_SOUR_FAIL)");
//	map.put("通过仓库和Tag类型得到标识数据源失败", "I18nHolder.format(I18nMessageCode.GET_TAG_SOUR_BY_WH_TAGTYPE_FAIL)");
//	map.put("加载跟单位有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_UNIT_SOUR_FAIL)");
//	map.put("展示添加操作页失败", "I18nHolder.format(I18nMessageCode.VIEW_ADD_OPER_FAIL)");
//	map.put("商品编码、条码为空", "I18nHolder.format(I18nMessageCode.PROCODE_BAR_IS_NULL)");
//	map.put("创建操作失败", "I18nHolder.format(I18nMessageCode.CREATE_OPER_FAIL)");
//	map.put("创建失败", "I18nHolder.format(I18nMessageCode.CREATE_FAIL)");
//	map.put("获取固定仓位信息失败", "I18nHolder.format(I18nMessageCode.GET_BIN_INFO_FAIL)");
//	map.put("未选择任务行项目", "I18nHolder.format(I18nMessageCode.NO_SELECT_TASK_ITEM)");
//	map.put("批量冻结操作失败", "I18nHolder.format(I18nMessageCode.BATCH_FROZEN_OPER_FAIL)");
//	map.put("批量删除仓位数量不能大于100", "I18nHolder.format(I18nMessageCode.BATCH_DELETE_BIN_NUM_NOTGTE_HUN)");
//	map.put("跳转修改冻结状态页面失败", "I18nHolder.format(I18nMessageCode.SKIP_UP_FROZEN_STATE_PAGE_FAIL)");
//	map.put("搜索关键词为空", "I18nHolder.format(I18nMessageCode.SEA_KEY_WORD_NULL)");
//	map.put("国条为空", "I18nHolder.format(I18nMessageCode.UPD_BIN_PUT_STATE_TO_NO_DIST_EPT)");
//	map.put("查询仓位使用率报表失败", "I18nHolder.format(I18nMessageCode.QUE_BIN_USE_REPORT_FAIL)");
//	map.put("仓位使用率报表导出失败!", "I18nHolder.format(I18nMessageCode.BIN_USE_REPORT_EXPORT_FAIL)");
//	map.put("请传仓位ID", "I18nHolder.format(I18nMessageCode.PLEASE_TRAS_BIN_ID)");
//	map.put("请传正确的冻结状态", "I18nHolder.format(I18nMessageCode.PLEASE_TRANS_COR_FROZEN_STATE)");
//	map.put("resetMixStorageValidationFlag失败", "I18nHolder.format(I18nMessageCode.RESET_ALLMIX_VALIDA_FLAG_FAIL)");
//	map.put("resetAllMixStorageValidationFlag失败", "I18nHolder.format(I18nMessageCode.RESET_MIX_VALIDA_FLAG_FAIL)");
//	map.put("获取添加信息失败", "I18nHolder.format(I18nMessageCode.GET_ADD_INFO_FAIL)");
//	map.put("获取更新信息失败", "I18nHolder.format(I18nMessageCode.GET_UPDATE_INFO_FAIL)");
//	map.put("提交的仓库ID为空或者不合规范", "I18nHolder.format(I18nMessageCode.COMMIT_WH_ID_NULL_OR_ERROR)");
//	map.put("提交操作失败", "I18nHolder.format(I18nMessageCode.COMMIT_OPER_FAIL)");
//	map.put("获取添加数据失败", "I18nHolder.format(I18nMessageCode.GET_ADD_DATA_FAIL)");
//	map.put("门店不存在", "I18nHolder.format(I18nMessageCode.STORE_NOEXIT)");
//	map.put("该直流采购单无该门店可播种商品", "I18nHolder.format(I18nMessageCode.ZL_POST_NO_STORE_PRODUCT)");
//	map.put("国条为空", "I18nHolder.format(I18nMessageCode.EAN_NULL)");
//	map.put("该商品不存在", "I18nHolder.format(I18nMessageCode.CUR_PRODUCT_NOEXIT)");
//	map.put("外向订单行项目为空", "I18nHolder.format(I18nMessageCode.POST_ORDER_ITEM_NULL)");
//	map.put("提交直流播种信息为空", "I18nHolder.format(I18nMessageCode.COMMIT_ZL_INFO_NULL)");
//	map.put("客户id为空", "I18nHolder.format(I18nMessageCode.CUSTOMER_ID_NULL)");
//	map.put("采购单为空", "I18nHolder.format(I18nMessageCode.POST_NULL)");
//	map.put("采购订单不存在", "I18nHolder.format(I18nMessageCode.POST_ORDER_NOEXIT)");
//	map.put("该商品在该直流采购订单不存在", "I18nHolder.format(I18nMessageCode.PRODUCT_ZL_POST_ORDER_NOEXIT)");
//	map.put("直流行项目信息查询失败", "I18nHolder.format(I18nMessageCode.ZL_ITEM_INFO_QUE_FAIL)");
//	map.put("容器码未打印，不在起始号段内", "I18nHolder.format(I18nMessageCode.CONT_CODE_NO_PRINT_START_RANGE)");
//	map.put("判断容器在库存中使用情况异常", "I18nHolder.format(I18nMessageCode.JUDGE_CONT_IN_STOCK_USE_EPT)");
//	map.put("判断容器在入库中使用情况异常", "I18nHolder.format(I18nMessageCode.JUDGE_CONT_GR_USE_EPT)");
//	map.put("客户编码不同，不允许混播", "I18nHolder.format(I18nMessageCode.CUS_CODE_DIFF_NO_MIX_SEND)");
//	map.put("查询容器商品库存异常", "I18nHolder.format(I18nMessageCode.QUERY_CONT_PRODUCT_STOCK_EPT)");
//	map.put("商品课组不同，不允许混播", "I18nHolder.format(I18nMessageCode.PRODUCT_GROUP_DIFF_NO_MIX_SEND)");
//	map.put("打印机编码为空", "I18nHolder.format(I18nMessageCode.PRINT_CODE_NULL)");
//	map.put("打印机格式错误", "I18nHolder.format(I18nMessageCode.PRINT_FORMAT_ERROR)");
//	map.put("打印机编码错误", "I18nHolder.format(I18nMessageCode.PRINT_CODE_ERROR)");
//	map.put("商品基本单位不存在", "I18nHolder.format(I18nMessageCode.PRODUCT_BASE_UNIT_NOEXIT)");
//	map.put("包材不存在", "I18nHolder.format(I18nMessageCode.HU_NOEXIT)");
//	map.put("包材单位非重量单位", "I18nHolder.format(I18nMessageCode.HU_UNIT_NO_WEIGHT_UNIT)");
//	map.put("包材单位不存在", "I18nHolder.format(I18nMessageCode.HU_UNIT_NOEXIT)");
//	map.put("分配系数为空", "I18nHolder.format(I18nMessageCode.DIST_COEFF_NULL)");
//	map.put("标件重量为空", "I18nHolder.format(I18nMessageCode.J_NUT_WEIGHT_NULL)");
//	map.put("分配系数不能为负数", "I18nHolder.format(I18nMessageCode.DIST_COEFF_NO_MINUS)");
//	map.put("打印机配置为空", "I18nHolder.format(I18nMessageCode.PRINT_CONF_NULL)");
//	map.put("确认方式为空", "I18nHolder.format(I18nMessageCode.CONFIRM_WAY_NULL)");
//	map.put("采购单号为空", "I18nHolder.format(I18nMessageCode.POST_NUM_NULL)");
//	map.put("分配比例为空", "I18nHolder.format(I18nMessageCode.DIST_SCALE_NULL)");
//	map.put("分配系数值不能超过100", "I18nHolder.format(I18nMessageCode.DIST_COEFF_PASS_HUNDRED)");
//	map.put("请输HU编码", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_HUCODE)");
//	map.put("请输入容器码", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_CONTCODE)");
//	map.put("请输入仓位编码", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_BIN_CODE)");
//	map.put("请输入客户编码", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_CUS_CODE)");
//	map.put("容器码类型必须是虚拟类型", "I18nHolder.format(I18nMessageCode.CONT_CODE_TYPE_MUST_FICT)");
//	map.put("添加容器码成功", "I18nHolder.format(I18nMessageCode.ADD_CONT_CODE_SUCC)");
//	map.put("容器类型不存在", "I18nHolder.format(I18nMessageCode.CONT_TYPE_NOEXIT)");
//	map.put("系统异常，请重新扫描", "I18nHolder.format(I18nMessageCode.SYSTEM_EPT_PLEASE_SCAN)");
//	map.put("源容器码为空", "I18nHolder.format(I18nMessageCode.SOUR_CONT_CODE_NULL)");
//	map.put("目标容器码为空", "I18nHolder.format(I18nMessageCode.TARGET_CONT_CODE_NULL)");
//	map.put("客户编码不同", "I18nHolder.format(I18nMessageCode.CUS_CODE_DIFF)");
//	map.put("请输入目标容器码", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_TAGET_CONTCODE)");
//	map.put("与源容器编码一致，请重新扫描", "I18nHolder.format(I18nMessageCode.EQUALS_SOURCE_CONTCODE_SCAN)");
//	map.put("请选择合板拆分项目", "I18nHolder.format(I18nMessageCode.PLEASE_SELECT_PLY_SPLIT)");
//	map.put("合板拆分成功", "I18nHolder.format(I18nMessageCode.PLY_SPLIT_SUCC)");
//	map.put("容器码已合板，请扫描上级容器码", "I18nHolder.format(I18nMessageCode.CONT_PLY_SCAN_PARENT_CONT)");
//	map.put("仓库开关配置不存在", "I18nHolder.format(I18nMessageCode.WH_ON_CONF_NOEXIT)");
//	map.put("请输入源容器码", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_SOURCE_CONTCODE)");
//	map.put("目标容器码和源容器码相同", "I18nHolder.format(I18nMessageCode.TARG_CONTCODE_EQUALS_SOURCODE)");
//	map.put("大小店为空", "I18nHolder.format(I18nMessageCode.BIG_SMALL_NULL)");
//	map.put("波次号为空", "I18nHolder.format(I18nMessageCode.WAVE_NUM_NULL)");
//	map.put("提总类型为空", "I18nHolder.format(I18nMessageCode.PICK_TOTAL_TYPE_NULL)");
//	map.put("目标容器码不能为空", "I18nHolder.format(I18nMessageCode.TARGET_CONTCODE_NOTNULL)");
//	map.put("波次号不能为空", "I18nHolder.format(I18nMessageCode.WAVE_NUM_NOT_NULL)");
//	map.put("hu编码为空", "I18nHolder.format(I18nMessageCode.HU_CODE_NULL)");
//	map.put("提交数据为空", "I18nHolder.format(I18nMessageCode.COMMIT_DATA_NULL)");
//	map.put("拣配类型为空", "I18nHolder.format(I18nMessageCode.PICK_TYPE_NULL)");
//	map.put("确认数量不能都为空或小于等于0", "I18nHolder.format(I18nMessageCode.CONFIRM_NUM_NOT_EQUALS_LT_ZERO)");
//	map.put("提交表单信息不能为空", "I18nHolder.format(I18nMessageCode.COMMIT_FORM_INFO_NOTNULL)");
//	map.put("工单号为空", "I18nHolder.format(I18nMessageCode.WORK_NUM_NULL)");
//	map.put("可以加箱", "I18nHolder.format(I18nMessageCode.ALLOW_ADD_BOX)");
//	map.put("任务被锁定，请先解锁任务", "I18nHolder.format(I18nMessageCode.TASK_LOCK_PLEASE_UNLOCK)");
//	map.put("解除工单占用状态成功", "I18nHolder.format(I18nMessageCode.REMOVE_ORDER_EMPLOY_STA_SUCC)");
//	map.put("huCode为空", "I18nHolder.format(I18nMessageCode.HUCODE_NULL)");
//	map.put("查询hu类型异常", "I18nHolder.format(I18nMessageCode.QUERY_HU_TYPE_EPT)");
//	map.put("未查询到对应的hu类型", "I18nHolder.format(I18nMessageCode.NOQUE_HU_TYPE)");
//	map.put("HU类型可修改", "I18nHolder.format(I18nMessageCode.HU_TYPE_MODIFY)");
//	map.put("HU类型相同，无需修改", "I18nHolder.format(I18nMessageCode.HUTYPE_SAVE_NOMODIFY)");
//	map.put("该容器下已有商品，不允许修改HU类型", "I18nHolder.format(I18nMessageCode.CURCONT_PRO_NOALLOW_MODI_HUTYPE)");
//	map.put("商品国条为空", "I18nHolder.format(I18nMessageCode.PRODUCT_EAN_NULL)");
//	map.put("请输入正确的门店规模序号", "I18nHolder.format(I18nMessageCode.PLEASE_ENTER_COR_CUS_SCALE_NO)");
//	map.put("容器码类型为空", "I18nHolder.format(I18nMessageCode.CONTCODE_TYPE_NULL)");
//	map.put("容器码必输", "I18nHolder.format(I18nMessageCode.CONTCODE_MUST_ENTER)");
//	map.put("任务状态必传", "I18nHolder.format(I18nMessageCode.TASK_STATE_MUST_TRANS)");
//	map.put("任务状态输入错误", "I18nHolder.format(I18nMessageCode.TASK_STATE_ENTER_ERROR)");
//	map.put("容器码不存在，请核实", "I18nHolder.format(I18nMessageCode.CONTCODE_NOEXIT_CHECK)");
//	map.put("该商品不在这个容器上", "I18nHolder.format(I18nMessageCode.CUR_PRODUCT_NOEXIT_CONT)");
//	map.put("系统异常，请重试", "I18nHolder.format(I18nMessageCode.SYSTEM_ERROR_PLEASE_REPEAT)");
//	map.put("仓位或商品必输其一", "I18nHolder.format(I18nMessageCode.BIN_OR_PRO_MUST_ENTER)");
//	map.put("可用的托盘码", "I18nHolder.format(I18nMessageCode.USE_TRAY_CODE)");
//	map.put("重新创建仓库采购订单成功", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_POST_ORDER_SUCC)");
//	map.put("重新创建仓库采购订单出现异常", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_POST_ORDER_EPT)");
//	map.put("查看仓库订单生成关联日志发生异常", "I18nHolder.format(I18nMessageCode.VIEW_WH_ORDER_RELA_LOG_EPT)");
//	map.put("重新生成仓库客户订单成功", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_CUS_ORDER_SUCC)");
//	map.put("重新生成仓库客户订单失败", "I18nHolder.format(I18nMessageCode.RE_CREATE_WH_CUS_ORDER_FAIL)");
//	map.put("SourcePO单信息查询出现异常", "I18nHolder.format(I18nMessageCode.SOURCE_PO_QUE_EPT)");
//	map.put("PO单号为空", "I18nHolder.format(I18nMessageCode.PO_NUM_NULL)");
//	map.put("投单失败", "I18nHolder.format(I18nMessageCode.DELI_ORDER_FAIL)");
//	map.put("采购订单行项目ID为空", "I18nHolder.format(I18nMessageCode.POST_ORDER_ITEM_ID_NULL)");
//	map.put("关闭采购订单明细成功", "I18nHolder.format(I18nMessageCode.CLOSE_POST_ORDER_DETAIL_SUCC)");
//	map.put("采购订单ID为空", "I18nHolder.format(I18nMessageCode.POST_ORDER_ID_NULL)");
//	map.put("关闭采购订单成功", "I18nHolder.format(I18nMessageCode.CLOSE_POST_ORDER_SUCC)");
//	map.put("更新订单失败", "I18nHolder.format(I18nMessageCode.UPDATE_ORDER_FAIL)");
//	map.put("更新订单成功", "I18nHolder.format(I18nMessageCode.UPDATE_ORDER_SUCC)");
//	map.put("查看投单日志出现异常", "I18nHolder.format(I18nMessageCode.QUERY_DELI_LOG_EPT)");
//	map.put("冻结失败", "I18nHolder.format(I18nMessageCode.FROZEN_FAIL)");
//	map.put("SourcePODetail单信息查询出现异常", "I18nHolder.format(I18nMessageCode.SOURCEPODETAIL_QUERY_EPT)");
//	map.put("初始化直流关系表失败", "I18nHolder.format(I18nMessageCode.INIT_ZL_RELA_TABLE_FAIL)");
//	map.put("同步成功", "I18nHolder.format(I18nMessageCode.SYNC_SUCC)");
//	map.put("同步失败", "I18nHolder.format(I18nMessageCode.SYNC_FAIL)");
//	map.put("解冻失败", "I18nHolder.format(I18nMessageCode.THAW_FAIL)");
//	map.put("一键冻结操作已在后台执行，完成后将通知结果", "I18nHolder.format(I18nMessageCode.A_FROZEN_HANDLE_NOTIFY_RESULT)");
//	map.put("一键解冻操作已在后台执行，完成后将通知结果", "I18nHolder.format(I18nMessageCode.A_THAW_HANDLE_NOTIFY_RESULT)");
//	map.put("已冻结", "I18nHolder.format(I18nMessageCode.FROZEN)");
//	map.put("未冻结", "I18nHolder.format(I18nMessageCode.THAW)");
//	map.put("查看预约单更新日志出现异常", "I18nHolder.format(I18nMessageCode.VIEW_RESER_ORDER_UPDATE_LOG_EPT)");
//	map.put("预约单信息查询出现异常", "I18nHolder.format(I18nMessageCode.RESER_INFO_QUE_EPT)");
//	map.put("预约单单号为空", "I18nHolder.format(I18nMessageCode.RESER_ORDER_NUM_NULL)");
//	map.put("预约单Id为空", "I18nHolder.format(I18nMessageCode.RESER_ID_NULL)");
//	map.put("查看预约单操作日志出现异常", "I18nHolder.format(I18nMessageCode.QUE_RESER_OPER_LOG_EPT)");
//	map.put("SourceSO单信息查询出现异常", "I18nHolder.format(I18nMessageCode.SOURCESO_QUE_EPT)");
//	map.put("SO单号为空", "I18nHolder.format(I18nMessageCode.SO_NUM_NULL)");
//	map.put("发运拣配成功", "I18nHolder.format(I18nMessageCode.DELIV_PICK_SUCCESS)");
//	map.put("发运拣配失败", "I18nHolder.format(I18nMessageCode.DELIV_PICK_FAIL)");
//	map.put("客户订单ID为空", "I18nHolder.format(I18nMessageCode.CUS_ORDER_ID_NULL)");
//	map.put("客户订单ID列表为空", "I18nHolder.format(I18nMessageCode.CUS_ORDER_IDS_LIST_NULL)");
//	map.put("客户订单明细id为空", "I18nHolder.format(I18nMessageCode.CUS_ORDER_DETAIL_ID_NULL)");
//	map.put("客户订单单号为空", "I18nHolder.format(I18nMessageCode.CUS_ORDER_NUM_NULL)");
//	map.put("关闭客户订单明细成功", "I18nHolder.format(I18nMessageCode.CLOSE_CUS_ORDER_DETAIL_SUCCESS)");
//	map.put("查看交货单生成日志出现异常", "I18nHolder.format(I18nMessageCode.GET_POST_LOG_EPT)");
//	map.put("推送消息失败", "I18nHolder.format(I18nMessageCode.PUSH_MSG_FAIL)");
//	map.put("推送消息成功", "I18nHolder.format(I18nMessageCode.PUSH_MSG_SUCC)");
//	map.put("仓位无更多库存", "I18nHolder.format(I18nMessageCode.BIN_NOMORE_STOCK)");
//	map.put("根据仓位编码查询失败", "I18nHolder.format(I18nMessageCode.BIN_CODE_QUERY_FAIL)");
//	map.put("根据商品条码查询失败", "I18nHolder.format(I18nMessageCode.PRODUCT_EAN_QUERY_FAIL)");
//	map.put("没有查询到更多库存信息", "I18nHolder.format(I18nMessageCode.NO_QUERY_MORE_STOCK_INFO)");
//	map.put("根据条码或商品编码查询失败", "I18nHolder.format(I18nMessageCode.EAN_PROCODE_QUERY_NULL)");
//	map.put("容器编码为空", "I18nHolder.format(I18nMessageCode.CONTCODE_NULL)");
//	map.put("根据容器码查询失败", "I18nHolder.format(I18nMessageCode.CONTCODE_QUERY_FAIL)");
//	map.put("启用失败", "I18nHolder.format(I18nMessageCode.START_USE_FAIL)");
//	map.put("加载跟商品库存交易日志有关的主数据数据源失败", "I18nHolder.format(I18nMessageCode.LOAD_PROSTO_TRADE_LOGSOUR_FAIL)");
//	map.put("商品库存交易日志查询失败", "I18nHolder.format(I18nMessageCode.PRO_STOCK_TRADE_LOG_QUERY_FAIL)");
//	map.put("存储类型不能为空", "I18nHolder.format(I18nMessageCode.STOCK_TYPE_NOT_NULL)");
//	map.put("盘点类型为空", "I18nHolder.format(I18nMessageCode.CHECK_TYPE_NULL)");
//	map.put("按照商品盘点,商品不能为空", "I18nHolder.format(I18nMessageCode.ACCORD_PRO_CHECK_NOTNULL)");
//	map.put("盘点凭证正在创建,结果稍后通知", "I18nHolder.format(I18nMessageCode.CHECK_VOU_CREATING_NOFITY_LATER)");
//	map.put("盘点凭证创建失败", "I18nHolder.format(I18nMessageCode.CHECK_VOU_CREATE_FAIL)");
//	map.put("获取新增数据异常", "I18nHolder.format(I18nMessageCode.GET_ADD_DATA_EPT)");
//	map.put("无容差", "I18nHolder.format(I18nMessageCode.NO_ALW)");
//	map.put("有容差", "I18nHolder.format(I18nMessageCode.ALW)");
//	map.put("活动区域为空", "I18nHolder.format(I18nMessageCode.ACTIVE_AREA_NULL)");
//	map.put("标件类型不正确", "I18nHolder.format(I18nMessageCode.J_NUT_TYPE_ERROR)");
//	map.put("按照盘点活动获取盘点凭证异常", "I18nHolder.format(I18nMessageCode.CHECK_ACTIVE_GET_VOU_EPT)");
//	map.put("按照存储类型查询盘点凭证异常", "I18nHolder.format(I18nMessageCode.STORE_TYPE_QUERY_CHECK_VOU_FAIL)");
//	map.put("获取仓库存储类型异常", "I18nHolder.format(I18nMessageCode.GET_WH_STORE_TYPE_EPT)");
//	map.put("获取层数失败", "I18nHolder.format(I18nMessageCode.GET_PLIES_FAIL)");
//	map.put("获取标件类型失败", "I18nHolder.format(I18nMessageCode.GET_J_NUT_TYPE_FAIL)");
//	map.put("作业区域ID为空", "I18nHolder.format(I18nMessageCode.WORK_AREA_ID_NULL)");
//	map.put("解锁成功", "I18nHolder.format(I18nMessageCode.UNLOCK_SUCC)");
//	map.put("转换基本单位数量失败", "I18nHolder.format(I18nMessageCode.TRANS_BASE_UNIT_NUM_FAIL)");
//	map.put("商品条码为空", "I18nHolder.format(I18nMessageCode.PRO_EAN_NULL)");
//	map.put("BinId为空", "I18nHolder.format(I18nMessageCode.BIN_ID_NULL)");
//	map.put("通过条码获取盘点商品信息失败", "I18nHolder.format(I18nMessageCode.EAN_GET_CHECK_PRO_INFO_FAIL)");
//	map.put("商品ID为空", "I18nHolder.format(I18nMessageCode.PRO_ID_NULL)");
//	map.put("日期类型不正确", "I18nHolder.format(I18nMessageCode.DATA_TYPE_ERROR)");
//	map.put("日期为空", "I18nHolder.format(I18nMessageCode.DATA_NULL)");
//	map.put("获取到期日或者生产日期失败", "I18nHolder.format(I18nMessageCode.GET_ENDTIME_OR_STARTTIME_FAIL)");
//	map.put("检查容器码失败", "I18nHolder.format(I18nMessageCode.CHECK_CONTCODE_FAIL)");
//	map.put("凭证id集合为空", "I18nHolder.format(I18nMessageCode.VOU_ID_COLLECT_NULL)");
//	map.put("过账成功", "I18nHolder.format(I18nMessageCode.POST_SUCC)");
//	map.put("正在后台执行过账，结果将以消息推送通知", "I18nHolder.format(I18nMessageCode.POST_INBACK_NOTIFY_LATER)");
//	map.put("该仓库没有维护盘点过账任务的盘点步骤配置", "I18nHolder.format(I18nMessageCode.CUR_WH_DEF_POST_TASK_STEP_CONF)");
//	map.put("盘点提交出现异常", "I18nHolder.format(I18nMessageCode.CHECK_COMMIT_EPT)");
//	map.put("凭证ID不能为空", "I18nHolder.format(I18nMessageCode.VOU_ID_NOT_NULL)");
//	map.put("通过ID查找凭证数据为空", "I18nHolder.format(I18nMessageCode.ID_QUE_VOU_NULL)");
//	map.put("盘点详情查看出现异常", "I18nHolder.format(I18nMessageCode.CHECK_DETAIL_VIEW_EPT)");
//	map.put("盘点空仓位出现异常", "I18nHolder.format(I18nMessageCode.CHECK_NULL_BIN_EPT)");
//	map.put("凭证参数为空;", "I18nHolder.format(I18nMessageCode.VOU_PARAM_NULL)");
//	map.put("凭证ID为空;", "I18nHolder.format(I18nMessageCode.VOU_ID_NULL)");
//	map.put("商品ID为空;", "I18nHolder.format(I18nMessageCode.PRODUCT_ID_NULL)");
//	map.put("标件类型为空;", "I18nHolder.format(I18nMessageCode.J_NUT_TYPE_NULL)");
//	map.put("作业区域ID为空;", "I18nHolder.format(I18nMessageCode.WORK_AREA_ID_NULL)");
//	map.put("盘点凭证ID列表为空", "I18nHolder.format(I18nMessageCode.CHECK_VOU_ID_LIST_NULL)");
//	map.put("获取盘点进度报表失败:", "I18nHolder.format(I18nMessageCode.GET_CHECK_RATE_REPORT_FAIL)");
//	map.put("获取盘点进度报表数据为空", "I18nHolder.format(I18nMessageCode.GET_CHECK_REPORT_NULL)");
//	map.put("获取盘点差异报表失败", "I18nHolder.format(I18nMessageCode.GET_CHECK_DIFF_REPORT_FAIL)");
//	map.put("获取盘点差异报表数据为空", "I18nHolder.format(I18nMessageCode.GET_CHECK_DIFF_REPORT_NULL)");
    }
}
